### ISSUE TITLE
[🐛BUG] tensor 的 dtype 在不同系统中不一致.

### ISSUE THREAD

**Issue by kaozhechi** [RUCAIBox/RecBole#1012]
跑BPR跑last-fm数据集，评测用mode: uni100
Traceback (most recent call last):
  File "C:/notC/TRUST/RecBole-master/run_recbole.py", line 25, in <module>
    run_recbole(model=args.model, dataset=args.dataset, config_file_list=config_file_list)
  File "C:\notC\TRUST\RecBole-master\recbole\quick_start\quick_start.py", line 60, in run_recbole
    train_data, valid_data, saved=saved, show_progress=config['show_progress']
  File "C:\notC\TRUST\RecBole-master\recbole\trainer\trainer.py", line 334, in fit
    valid_score, valid_result = self._valid_epoch(valid_data, show_progress=show_progress)
  File "C:\notC\TRUST\RecBole-master\recbole\trainer\trainer.py", line 196, in _valid_epoch
    valid_result = self.evaluate(valid_data, load_best_model=False, show_progress=show_progress)
  File "C:\notC\anaconda\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\notC\TRUST\RecBole-master\recbole\trainer\trainer.py", line 459, in evaluate
    interaction, scores, positive_u, positive_i = eval_func(batched_data)
  File "C:\notC\TRUST\RecBole-master\recbole\trainer\trainer.py", line 407, in _neg_sample_batch_eval
    scores[row_idx, col_idx] = origin_scores
IndexError: tensors used as indices must be long, byte or bool tensors
这是为什么呀

**Comment by Sherry-XLL** [comment]
@kaozhechi 可能是不同系统的默认设置不同，使得 `row_idx` 这个 tensor 的 `dtype` 在不同系统中不一致，我在 Linux 服务器上运行得到的 `row_idx` 的 dtype 类型是 `torch.int64`，所以可以正常运行。你可以试着改变 `row_idx` 的 `dtype` 类型再尝试一下。

**Comment by WhutTjk** [comment]
@Sherry-XLL 同样出现此问题，希望下一个版本可以解决啊😘
