### ISSUE TITLE
 yelp data,use GRU4Rec model Error🐛BUG] 用一句话描述您的问题。

### ISSUE THREAD

**Issue by dola456** [RUCAIBox/RecBole#1033]
when I use yelp data ,run GRU4Rec model Error
my yelp.yaml is the following:
# dataset config
field_separator: "\t"
seq_separator: " "
USER_ID_FIELD: user_id
ITEM_ID_FIELD: business_id
RATING_FIELD: stars
TIME_FIELD: date
LABEL_FIELD: label
NEG_PREFIX: neg_
load_col:
  inter: [user_id, business_id, stars]
user_inter_num_interval: "[15,inf)"
item_inter_num_interval: "[15,inf)"
val_interval:
  stars: "[3,inf)"
# training and evaluation
epochs: 50
train_batch_size: 4096
eval_batch_size: 409600
valid_metric: MRR@10
# model
embedding_size: 64
training_neg_sample_num: 100
neg_sampling: ~
loss_type: 'CE'

run:python run_recbole.py --dataset=yelp --config_files=yelp.yaml
error:
Traceback (most recent call last):
  File "run_recbole.py", line 29, in <module>
    run_recbole(model=args.model, dataset=args.dataset, config_file_list=config_file_list)
  File "D:\RecommenderRL\RecBole-master\recbole\quick_start\quick_start.py", line 47, in run_recbole
    train_data, valid_data, test_data = data_preparation(config, dataset)
  File "D:\RecommenderRL\RecBole-master\recbole\data\utils.py", line 99, in data_preparation
    built_datasets = dataset.build()
  File "D:\RecommenderRL\RecBole-master\recbole\data\dataset\sequential_dataset.py", line 194, in build
    return super().build()
  File "D:\RecommenderRL\RecBole-master\recbole\data\dataset\dataset.py", line 1465, in build
    self._change_feat_format()
  File "D:\RecommenderRL\RecBole-master\recbole\data\dataset\sequential_dataset.py", line 49, in _change_feat_format
    self.data_augmentation()
  File "D:\RecommenderRL\RecBole-master\recbole\data\dataset\sequential_dataset.py", line 96, in data_augmentation
    self.sort(by=[self.uid_field, self.time_field], ascending=True)
  File "D:\RecommenderRL\RecBole-master\recbole\data\dataset\dataset.py", line 1456, in sort
    self.inter_feat.sort(by=by, ascending=ascending)
  File "D:\RecommenderRL\RecBole-master\recbole\data\interaction.py", line 304, in sort
    raise ValueError(f'[{b}] is not exist in interaction [{self}].')
ValueError: [date] is not exist in interaction [The batch_size of interaction: 1777765
    user_id, torch.Size([1777765]), cpu, torch.int64
    business_id, torch.Size([1777765]), cpu, torch.int64
    stars, torch.Size([1777765]), cpu, torch.float32

**Comment by chenyuwuxin** [comment]
@dola456 Hello, thanks for your attention to RecBole!
This may be because you did not load the `date` field.
You can try the following `load_col` settings:
```
load_col:
  inter: [user_id, business_id, stars, date]
```
I hope my answer can help you.
