### ISSUE TITLE
[🐛BUG] Load Pre-trained Item Embeddings

### ISSUE THREAD

**Issue by pintonos** [RUCAIBox/RecBole#1040]
I am trying to utilize your implementation for pre-trained embeddings according to: 

[Load Pre-trained Embedding](https://recbole.io/docs/v0.1.2/user_guide/usage/load_pretrained_embedding.html)

However, following error appears:

```
Traceback (most recent call last):
  File "C:/Users/apein/Documents/projects/humrecsys/seq-rec/run_emb.py", line 29, in <module>
    dataset = create_dataset(config)
  File "C:\Users\apein\.virtualenvs\humrecsys-Aky0O99T\lib\site-packages\recbole\data\utils.py", line 41, in create_dataset
    return SequentialDataset(config)
  File "C:\Users\apein\.virtualenvs\humrecsys-Aky0O99T\lib\site-packages\recbole\data\dataset\sequential_dataset.py", line 36, in __init__
    super().__init__(config)
  File "C:\Users\apein\.virtualenvs\humrecsys-Aky0O99T\lib\site-packages\recbole\data\dataset\dataset.py", line 96, in __init__
    self._from_scratch()
  File "C:\Users\apein\.virtualenvs\humrecsys-Aky0O99T\lib\site-packages\recbole\data\dataset\dataset.py", line 108, in _from_scratch
    self._data_processing()
  File "C:\Users\apein\.virtualenvs\humrecsys-Aky0O99T\lib\site-packages\recbole\data\dataset\dataset.py", line 158, in _data_processing
    self._preload_weight_matrix()
  File "C:\Users\apein\.virtualenvs\humrecsys-Aky0O99T\lib\site-packages\recbole\data\dataset\dataset.py", line 533, in _preload_weight_matrix
    token_num = self.num(preload_id_field)
  File "C:\Users\apein\.virtualenvs\humrecsys-Aky0O99T\lib\site-packages\recbole\data\dataset\dataset.py", line 989, in num
    return len(self.field2id_token[field])
KeyError: 'iid'
```

My Config file:

```
data_path: "../data/"
additional_feat_suffix: [itememb]

USER_ID_FIELD: session_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp

load_col:
    inter: [session_id, item_id, timestamp]
    itememb: [iid, item_emb]

fields_in_same_space: [[iid, item_id]]
preload_weight:
    iid: item_emb

# Training and evaluation config
...
```

Here I use item embeddings, but its also the same error when using the exact same config as described in the link (user embeddings). Do I miss something here?

**Comment by Sherry-XLL** [comment]
@pintonos Hello, there is no `item` column when you load data, so pre-training item embeddings can be loaded directly like this:
```python
USER_ID_FIELD: session_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp

load_col:
    inter: [session_id, item_id, timestamp]
    item: [item_id, item_emb]
```
And your file with item embeddings should be `[dataset].item` as follows:
item_id:token | item_emb:float_seq
-- | --
1 | -115.08 13.60 113.69
2 | -130.97 263.05 -129.88

In your model, item embedding matrix can be initialized by your pre-trained embedding vectors as following:
```python
class YourModel(GeneralRecommender):
    def __init__(self, config, dataset):
            pretrained_item_emb = dataset.item_feat['item_emb']
            self.item_embedding = nn.Embedding.from_pretrained(torch.from_numpy(pretrained_item_emb))
```
Please notice that when you use pre-trained embeddings, you should put `self.apply(xavier_uniform_initialization)` in the right place in case the pre-training vectors are overwritten.

**Comment by pintonos** [comment]
Hi! Thanks for your help.
I would like to seperate embeddings from normal item features so my config now looks like this:
```
additional_feat_suffix: [itememb]

USER_ID_FIELD: session_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp

load_col:
    inter: [session_id, item_id, timestamp]
    item: [item_id, artist_id]
    itememb: [iid, item_emb]

fields_in_same_space: [[iid, item_id]]
```
Now i get following error:
```
Traceback (most recent call last):
  File "C:/Users/apein/Documents/projects/humrecsys/seq-rec/run_emb.py", line 34, in <module>
    train_data, valid_data, test_data = data_preparation(config, dataset)
  File "C:\Users\apein\.virtualenvs\humrecsys-Aky0O99T\lib\site-packages\recbole\data\utils.py", line 99, in data_preparation
    built_datasets = dataset.build()
  File "C:\Users\apein\.virtualenvs\humrecsys-Aky0O99T\lib\site-packages\recbole\data\dataset\sequential_dataset.py", line 194, in build
    return super().build()
  File "C:\Users\apein\.virtualenvs\humrecsys-Aky0O99T\lib\site-packages\recbole\data\dataset\dataset.py", line 1465, in build
    self._change_feat_format()
  File "C:\Users\apein\.virtualenvs\humrecsys-Aky0O99T\lib\site-packages\recbole\data\dataset\sequential_dataset.py", line 44, in _change_feat_format
    super()._change_feat_format()
  File "C:\Users\apein\.virtualenvs\humrecsys-Aky0O99T\lib\site-packages\recbole\data\dataset\dataset.py", line 972, in _change_feat_format
    setattr(self, feat_name, self._dataframe_to_interaction(feat))
  File "C:\Users\apein\.virtualenvs\humrecsys-Aky0O99T\lib\site-packages\recbole\data\dataset\dataset.py", line 1780, in _dataframe_to_interaction
    new_data[k] = torch.LongTensor(value)
TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.
```
It seems the `iid:token` column from the embeddings file is loaded as string according to `def _load_feat(self, filepath, source)`.

My `.itememb` embeddings file looks like this:
```
iid:token	item_emb:float_seq
0	0.19 -0.17 0.02
```

**Comment by Sherry-XLL** [comment]
@pintonos 您好，您查看的文档版本是 v0.1.2，之前的版本里我们使用了 `fields_in_same_space` 来对齐 `additional_feat`。但在我们最新的 1.0.0 版本中，我们已经删去了 `fields_in_same_space` 的相关配置，改为了 `alias_of_item_id`，正确的配置如下，详情可以参考我们最新的 1.0.0 版本的文档 [Load Pre-trained Embedding](https://recbole.io/docs/user_guide/usage/load_pretrained_embedding.html#load-pre-trained-embedding)。
```python
additional_feat_suffix: [itememb]

USER_ID_FIELD: session_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp

load_col:
    inter: [session_id, item_id, timestamp]
    item: [item_id, artist_id]
    itememb: [iid, item_emb]

alias_of_item_id: [iid]
preload_weight:
    iid: item_emb
```

**Comment by pintonos** [comment]
Oh, that was absolutely my fault! Thanks for the information and for your great work on this!
