### ISSUE TITLE
[🐛BUG] 无标签（全正例）数据集用DecisionTree模型训练出错

### ISSUE THREAD

**Issue by FineArtz** [RUCAIBox/RecBole#1067]
对于无标签（全正例）数据集，按照文档中的说明，可以通过设置`neg_sampling`参数通过负采样训练。但我在用xgboost模型训练时，出现错误
```
Traceback (most recent call last):
  File "run_recbole.py", line 26, in <module>
    run_recbole(model=args.model, dataset=args.dataset, config_file_list=config_file_list)
  File "RecBole/recbole/quick_start/quick_start.py", line 65, in run_recbole
    best_valid_score, best_valid_result = trainer.fit(
  File "RecBole/recbole/trainer/trainer.py", line 775, in fit
    self._train_at_once(train_data, valid_data)
  File "RecBole/recbole/trainer/trainer.py", line 869, in _train_at_once
    self.dtrain = self._interaction_to_lib_datatype(train_data)
  File "RecBole/recbole/trainer/trainer.py", line 859, in _interaction_to_lib_datatype
    data, label = self._interaction_to_sparse(dataloader)
  File "RecBole/recbole/trainer/trainer.py", line 741, in _interaction_to_sparse
    return cur_data, interaction_np[self.label_field]
KeyError: 'label'
```
报错来自于DecisionTreeTrainer在train之前对数据做的[预处理](https://github.com/RUCAIBox/RecBole/blob/310ec8b9905bcb2f8ce09226768d47413049d861/recbole/trainer/trainer.py#L692)`_interaction_to_sparse()`，其中包含
```
# Line 701 ~ 702, in _interaction_to_sparse(), recbole/trainer/trainer.py
interaction = dataloader.dataset[:]
interaction_np = interaction.numpy()

# Line 741, in the same file
return cur_data, interaction_np[self.label_field] # Error
```
看上去是数据集中并没有实际加入`LABEL_FIELD`导致的错误。

另外，我还查看了`tests/model`里的相关内容，发现所用的test数据集通过`rating`和`threshold`产生了label，并且没有进行负采样。如果不设置`threshold`，运行
```
python run_recbole.py --model xgboost --dataset test --config_files tests/model/test_model.yaml
```
会出现同样的错误。

不知道我的理解是否正确？是否有办法用xgboost加上负采样训练呢？

**Comment by chenyuwuxin** [comment]
@FineArtz 您好，感谢您的关注！对于Xgboost或者context-aware相关的模型，不能用负采样的方式构造负例，因为在构造负例时，无法设置负例的交互context信息(例如交互的时间)，因此要显式地通过threhold设置label的方式设置负例。

**Comment by FineArtz** [comment]
> @FineArtz 您好，感谢您的关注！对于Xgboost或者context-aware相关的模型，不能用负采样的方式构造负例，因为在构造负例时，无法设置负例的交互context信息(例如交互的时间)，因此要显式地通过threhold设置label的方式设置负例。

我明白了，感谢解答！
