### ISSUE TITLE
[🐛BUG] RepeatNet Loss Error

### ISSUE THREAD

**Issue by pintonos** [RUCAIBox/RecBole#1088]
Trying to run the RepeatNet model for sequential recommendation. Got this error:

```
Traceback (most recent call last):
  File "C:/Users/apein/Documents/projects/humrecsys/seq_rec/run.py", line 76, in <module>
    main(args=args)
  File "C:/Users/apein/Documents/projects/humrecsys/seq_rec/run.py", line 62, in main
    valid_score, valid_result = trainer.fit(
  File "C:\Users\apein\.virtualenvs\humrecsys-Aky0O99T\lib\site-packages\recbole\trainer\trainer.py", line 319, in fit
    self._generate_train_loss_output(epoch_idx, training_start_time, training_end_time, train_loss)
  File "C:\Users\apein\.virtualenvs\humrecsys-Aky0O99T\lib\site-packages\recbole\trainer\trainer.py", line 258, in _generate_train_loss_output
    train_loss_output += set_color('train loss', 'blue') + ': ' + des % losses
TypeError: must be real number, not NoneType
```

I am using `CE` as `loss_type` with no negative sampling. Other models work fine with the same settings and dataset.

**Comment by Sherry-XLL** [comment]
@pintonos Hello, RepeatNet works well in our ml-1m dataset, so I can't reproduce your results. Are you having problems with your own data set?

**Comment by nsane9129** [comment]
What was the solution ?
