### ISSUE TITLE
切换数据集后，多数模型报此错误，求教如何调试

### ISSUE THREAD

**Issue by Figfavture** [RUCAIBox/RecBole#1121]
Traceback (most recent call last):
  File "E:/RecBole/run.py", line 6, in <module>
    run_recbole(model='FDSA', dataset='douban', config_dict=parameter_dict)
  File "E:\RecBole\recbole\quick_start\quick_start.py", line 52, in run_recbole
    model = get_model(config['model'])(config, train_data.dataset).to(config['device'])
  File "E:\RecBole\recbole\model\sequential_recommender\fdsa.py", line 57, in __init__
    dataset, self.hidden_size, self.selected_features, self.pooling_mode, self.device
  File "E:\RecBole\recbole\model\layers.py", line 831, in __init__
    self.get_fields_name_dim()
  File "E:\RecBole\recbole\model\layers.py", line 586, in get_fields_name_dim
    if self.dataset.field2type[field_name] == FeatureType.TOKEN:
KeyError: 'class'

**Comment by chenyuwuxin** [comment]
@Figfavture 您好，感谢您的关注！
这个问题来自于配置文件的错误，请在你的yaml文件中设置`selected_features`字段来指明选中的物品的特征。
例如，对于ml-100k数据集，它的默认配置为`selected_features: ['class']`。

**Comment by Figfavture** [comment]
非常感谢您热心的回复。关于物品特征字段的选择，我对代码进行调试后发现，当使用douban数据集后，field2type中并无class字段，那么我可以在配置文件中选择item_id字段进行训练吗

**Comment by chenyuwuxin** [comment]
@Figfavture 当然，'class' 特征是针对ml-100k数据集的设置。你需要在`selected_features`指定你选中的douban数据集的物品特征。如果选中item_id，设置：selected_features: ['item_id']。
