### ISSUE TITLE
切换batch size不影响显存使用大小？

### ISSUE THREAD

**Issue by sxhysj** [RUCAIBox/RecBole#1184]
我用不同的batchsize做训练和验证，但似乎显存都不变化。显示如下错误：
```
09 Mar 01:52    INFO  [Training]: train_batch_size = [512] negative sampling: [{'uniform': 1}]
09 Mar 01:52    INFO  [Evaluation]: eval_batch_size = [512] eval_args: [{'group_by': 'user', 'order': 'RO', 'split': {'RS': [0.8, 0.1, 0.1]}, 'mode': 'full'}]
Traceback (most recent call last):
  File "run.py", line 17, in <module>
    run_recbole(model=args.model, dataset=args.dataset, config_file_list=config_file_list)
  File "/home/huanchen/miniforge3/envs/pytorch/lib/python3.8/site-packages/recbole/quick_start/quick_start.py", line 49, in run_recbole
    model = get_model(config['model'])(config, train_data.dataset).to(config['device'])
  File "/home/huanchen/miniforge3/envs/pytorch/lib/python3.8/site-packages/recbole/model/general_recommender/recvae.py", line 125, in __init__
    self.history_item_value = self.history_item_value.to(self.device)
RuntimeError: CUDA out of memory. Tried to allocate 7.75 GiB (GPU 0; 23.68 GiB total capacity; 15.51 GiB already allocated; 6.56 GiB free; 15.51 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

有什么建议吗？

**Comment by chenyuwuxin** [comment]
@sxhysj 感谢您的关注！
可能是数据集的物品数量太多，导致全评测模式占用的显存过多。可以尝试更换采样模式，例如设置 `mode: 'pop100'`。

**Comment by sxhysj** [comment]
> @sxhysj 感谢您的关注！ 可能是数据集的物品数量太多，导致全评测模式占用的显存过多。可以尝试更换采样模式，例如设置 `mode: 'pop100'`。

试过了，还是一样的结果。我贴出我的配置文件：
```
# Atomic File Format
field_separator: ","
seq_separator: " "

# Common Features
USER_ID_FIELD: customer_id
ITEM_ID_FIELD: article_id

# Selectively Loading
load_col:
    #inter: [user_id, item_id, rating, timestamp]
    inter: [t_dat, customer_id, article_id, price, sales_channel_id]
    item: [article_id,product_code,prod_name,product_type_no,product_type_name,product_group_name,graphical_appearance_no,graphical_appearance_name,colour_group_code,colour_group_name,perceived_colour_value_id,perceived_colour_value_name,perceived_colour_master_id,perceived_colour_master_name,department_no,department_name,index_code,index_name,index_group_no,index_group_name,section_no,section_name,garment_group_no,garment_group_name,detail_desc]
    user: [customer_id,FN,Active,club_member_status,fashion_news_frequency,age,postal_code]
unload_col: ~
unused_col: ~

eval_args:
    group_by: user
    order: RO
    split: {'RS': [0.8,0.1,0.1]}
    mode: pop100
metrics: ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision', 'MAP']
topk: 12
valid_metric: MRR@12
metric_decimal_place: 4

#traning parameters
train_batch_size: 2048
eval_batch_size: 2048

#filter out no interaction users
user_inter_num_interval: "[1,inf)"
```

**Comment by chenyuwuxin** [comment]
@sxhysj 你好，这种情况是由于数据集太大了，导致初始化过程显存无法承载RecVAE模型记录的每个用户的历史交互物品，所以根本无法展开训练，所以切换batch_size并不能影响程序申请的显存容量。一个可能的解决方法是过滤掉某些交互数量过低的用户，即设置`user_inter_num_interval: "[3,inf)"`，数值可视情况调整。

**Comment by sxhysj** [comment]
> @sxhysj 你好，这种情况是由于数据集太大了，导致初始化过程显存无法承载RecVAE模型记录的每个用户的历史交互物品，所以根本无法展开训练，所以切换batch_size并不能影响程序申请的显存容量。一个可能的解决方法是过滤掉某些交互数量过低的用户，即设置`user_inter_num_interval: "[3,inf)"`，数值可视情况调整。

已成功
