### ISSUE TITLE
Completed an epoch of BERT4Rec model with customized config with steam data, but i got a pickling error PicklingError: Can't pickle <class 'recbole.model.sequential_recommender.bert4rec.BERT4Rec'>: it's not the same object as recbole.model.sequential_recommender.bert4rec.BERT4Rec

### ISSUE THREAD

**Issue by Jeriousman** [RUCAIBox/RecBole#1206]
The error says as ```PicklingError: Can't pickle <class 'recbole.model.sequential_recommender.bert4rec.BERT4Rec'>: it's not the same object as recbole.model.sequential_recommender.bert4rec.BERT4Rec```

I modified a bit of config to train Bert4Rec with steam data and tried to save data. This is my config
```
config_dict = {'neg_sampling' : None, 
                   'data_path': '/home/hojun/Python/Models/Recommender_systems/RecBole/run_example/dataset/steam_merged/merged/',
                   'load_col':
                       {
                       'inter': ['user_id', 'product_id', 'timestamp', 'play_hours']},
                       'LABEL_FIELD': 'play_hours',
                       'threshold': {'play_hours':1},
                       'ITEM_ID_FIELD': 'product_id',
                       'epochs': '10',
                       'save_dataset': True,
                       'save_dataloaders': True
                       }
```
Then did all the routine of functions inside run_recbole then finally I started the trainer.fit and it threw the error. I guess the error comes from saved= True. When False, nothing should be pickled so I do not get the error. Yet. I want to get it saved and want to know what the error is for.
```
best_valid_score, best_valid_result = trainer.fit(
    train_data, valid_data, saved=True, show_progress=config['show_progress']
)
```
```
Train     0:  99%|███████████████████████▊| 185/186 [00:53<00:00,  3.48it/s, GPU RAM: 5.29 G/7.80 G]GPU RAM: 5.29 G/7.80 G]GPU RAM: 5.29 G/7.80 G]Train     0:   9%|██▎                      | 17/186 [00:04<00:45,  3.69it/s, GPU RAM: 5.29 G/7.80 G]Train     0:  11%|██▋                      | 20/186 [00:06<00:45,  3.66it/s, GPU RAM: 5.29 G/7.80 G]]GPU RAM: 5.29 G/7.80 G]:  28%|███████                  | 53/186 [00:14<00:36,  3.68it/s, GPU RAM: 5.29 G/7.80 G]]Train     0:  30%|███████▌                 | 56/186 [00:15<00:34,  3.78it/s, GPU RAM: 5.29 G/7.80 G]:  38%|█████████▌               | 71/186 [00:20<00:42,  2.70it/s, GPU RAM: 5.29 G/7.80 G]:  38%|█████████▌               | 71/186 [00:20<00:42,  2.70it/s, GPU RAM: 5.29 G/7.80 G]]GPU RAM: 5.29 G/7.80 G]Train     0:  49%|████████████▎            | 92/186 [00:26<00:25,  3.63it/s, GPU RAM: 5.29 G/7.80 G]:  55%|█████████████▎          | 103/186 [00:29<00:23,  3.50it/s, GPU RAM: 5.29 G/7.80 G]]Train     0:  60%|██████████████▎         | 111/186 [00:31<00:22,  3.31it/s, GPU RAM: 5.29 G/7.80 G]GPU RAM: 5.29 G/7.80 G]:  70%|████████████████▉       | 131/186 [00:37<00:15,  3.55it/s, GPU RAM: 5.29 G/7.80 G]Train     0:  73%|█████████████████▌      | 136/186 [00:38<00:14,  3.52it/s, GPU RAM: 5.29 G/7.80 G]]GPU RAM: 5.29 G/7.80 G]GPU RAM: 5.29 G/7.80 G]Train     0:  83%|████████████████████    | 155/186 [00:44<00:08,  3.45it/s, GPU RAM: 5.29 G/7.80 G]:  87%|████████████████████▉   | 162/186 [00:46<00:06,  3.54it/s, GPU RAM: 5.29 G/7.80 G]]:  94%|██████████████████████▍ | 174/186 [00:50<00:03,  3.60it/s, GPU RAM: 5.29 G/7.80 G]Train     0:  96%|██████████████████████▉ | 178/186 [00:51<00:02,  3.62it/s, GPU RAM: 5.29 G/7.80 G]
25 Mar 14:51    INFO  epoch 0 training [time: 53.19s, train loss: 1361.1282]
Evaluate   : 100%|████████████████████████████| 9/9 [00:02<00:00,  4.28it/s, GPU RAM: 5.29 G/7.80 G]GPU RAM: 5.29 G/7.80 G]GPU RAM: 5.29 G/7.80 G]: 100%|████████████████████████████| 9/9 [00:02<00:00,  4.09it/s, GPU RAM: 5.29 G/7.80 G]
25 Mar 14:51    INFO  epoch 0 evaluating [time: 2.36s, valid_score: 0.037500]
25 Mar 14:51    INFO  valid result: 
recall@10 : 0.0748    mrr@10 : 0.0375    ndcg@10 : 0.0463    hit@10 : 0.0748    precision@10 : 0.0075
Traceback (most recent call last):

  File "/tmp/ipykernel_36240/1368664882.py", line 2, in <module>
    train_data, valid_data, saved=True, show_progress=config['show_progress']

  File "/home/hojun/Python/Models/Recommender_systems/RecBole/recbole/trainer/trainer.py", line 373, in fit
    self._save_checkpoint(epoch_idx, verbose=verbose)

  File "/home/hojun/Python/Models/Recommender_systems/RecBole/recbole/trainer/trainer.py", line 230, in _save_checkpoint
    torch.save(state, saved_model_file)

  File "/home/hojun/anaconda3/envs/recbole/lib/python3.7/site-packages/torch/serialization.py", line 380, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol)

  File "/home/hojun/anaconda3/envs/recbole/lib/python3.7/site-packages/torch/serialization.py", line 589, in _save
    pickler.dump(obj)

PicklingError: Can't pickle <class 'recbole.model.sequential_recommender.bert4rec.BERT4Rec'>: it's not the same object as recbole.model.sequential_recommender.bert4rec.BERT4Rec
```
I am not really sure what the error means. Could you give some solutions for the problem?

Thank you in advance.

**Comment by Wicknight** [comment]
@Jeriousman Hello, thanks for your attention to RecBole!
I speculate that one possible reason is that the code of model initialization to GPU and the code of 'trainer.fit()' are executed in different cells when running jupyter, resulting in the object of 'BERT4Rec' being changed.
