### ISSUE TITLE
Mismatch in length when running Repeatnet with default diginetica-session benchmark data.

### ISSUE THREAD

**Issue by Jeriousman** [RUCAIBox/RecBole#1220]
I basically ran the session_based_rec_example.py with slight adding of codes.

What I ran is as below.

```
import argparse
from logging import getLogger

from recbole.config import Config
from recbole.data import create_dataset
from recbole.data.utils import get_dataloader
from recbole.utils import init_logger, init_seed, get_model, get_trainer, set_color


def get_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--model', '-m', type=str, default='RepeatNet', help='Model for session-based rec.')
    parser.add_argument('--dataset', '-d', type=str, default='diginetica-session', help='Benchmarks for session-based rec.')
    parser.add_argument('--validation', action='store_true', help='Whether evaluating on validation set (split from train set), otherwise on test set.')
    parser.add_argument('--valid_portion', type=float, default=0.1, help='ratio of validation set.')
    return parser.parse_known_args()[0]


if __name__ == '__main__':
    args = get_args()

    # configurations initialization
    config_dict = {
        'USER_ID_FIELD': 'session_id',
        'load_col': None,
        'neg_sampling': None,
        'benchmark_filename': ['train', 'test'],
        'alias_of_item_id': ['item_id_list'],
        'topk': [20],
        'metrics': ['Recall', 'MRR'],
        'valid_metric': 'MRR@20'
    }

    config = Config(model=args.model, dataset=f'{args.dataset}', config_dict=config_dict)
    init_seed(config['seed'], config['reproducibility'])

    # logger initialization
    init_logger(config)
    logger = getLogger()

    logger.info(args)
    logger.info(config)

    # dataset filtering
    dataset = create_dataset(config)
    logger.info(dataset)
    dir(dataset)
    dataset.max_item_list_len

    # dataset splitting
    train_dataset, test_dataset = dataset.build()
    dir(test_dataset)
    if args.validation:
        train_dataset.shuffle()
        new_train_dataset, new_test_dataset = train_dataset.split_by_ratio([1 - args.valid_portion, args.valid_portion])
        train_data = get_dataloader(config, 'train')(config, new_train_dataset, None, shuffle=True)
        test_data = get_dataloader(config, 'test')(config, new_test_dataset, None, shuffle=False)
    else:
        train_data = get_dataloader(config, 'train')(config, train_dataset, None, shuffle=True)
        test_data = get_dataloader(config, 'test')(config, test_dataset, None, shuffle=False)
```

Then I took some code snippets from trainer and repeatnet to get interaction.

```
##getting interaction data
from tqdm import tqdm
iter_data = (
            tqdm(
                train_data,
                total=len(train_data),
                ncols=100))#,
                # desc=set_color(f"Train {epoch_idx:>5}", 'pink')))


model = RepeatNet(config, dataset)
model.train()
# x = BERT4Rec(config, train_dataloader)

for batch_idx, interaction in enumerate(iter_data):
    interaction = interaction.to('cpu')
    # optimizer.zero_grad()
    # losses = loss_func(interaction)
    break
```
The problem is in interaction, max_len is 69 even though config limits max_len to 50.

This is part of my config below.
```
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
```

But interaction is as below.
```
interaction
Out[32]: 
The batch_size of interaction: 2048
    session_id, torch.Size([2048]), cpu, torch.int64
    item_id_list, torch.Size([2048, 69]), cpu, torch.int64
    item_id, torch.Size([2048]), cpu, torch.int64
    item_length, torch.Size([2048]), cpu, torch.int64
```
As you can see, item_id_list is not [2048, 50] but [2048, 69].  So when I run the following code below, I get this error below.

```
    # model loading and initialization
    model = get_model(config['model'])(config, train_data.dataset).to(config['device'])
    logger.info(model)

    # trainer loading and initialization
    trainer = get_trainer(config['MODEL_TYPE'], config['model'])(config, model)

    # model training and evaluation
    test_score, test_result = trainer.fit(
        train_data, test_data, saved=True, show_progress=config['show_progress']
    )
```
The error 
```
Traceback (most recent call last):

  File "/tmp/ipykernel_61822/2143174111.py", line 9, in <module>
    train_data, test_data, saved=True, show_progress=config['show_progress']

  File "/home/hojun/Python/Models/Recommender_systems/RecBole/recbole/trainer/trainer.py", line 335, in fit
    train_loss = self._train_epoch(train_data, epoch_idx, show_progress=show_progress)

  File "/home/hojun/Python/Models/Recommender_systems/RecBole/recbole/trainer/trainer.py", line 181, in _train_epoch
    losses = loss_func(interaction)

  File "/home/hojun/Python/Models/Recommender_systems/RecBole/recbole/model/sequential_recommender/repeatnet.py", line 156, in calculate_loss
    prediction = self.forward(item_seq, item_seq_len)

  File "/home/hojun/Python/Models/Recommender_systems/RecBole/recbole/model/sequential_recommender/repeatnet.py", line 135, in forward
    self.repeat_explore = self.repeat_explore_mechanism.forward(all_memory=all_memory, last_memory=last_memory)

  File "/home/hojun/Python/Models/Recommender_systems/RecBole/recbole/model/sequential_recommender/repeatnet.py", line 245, in forward
    output_ere = self.tanh(all_memory + last_memory)  ##now dimenstion matches

RuntimeError: The size of tensor a (69) must match the size of tensor b (50) at non-singleton dimension 1
```

My questions arise here.
1. Am I correct that length mismatch causes the problem?
2. Why max_len is not cut at 50?
3. How can I fix this problem?

Thank you in advance.

**Comment by hyp1231** [comment]
1. Yes, the issue is caused by length mismatching.
2. As when we run in `benchmark_filename` mode, RecBole will do nothing about data preprocessing, including sequences truncation.
3. I suggest slightly modifying the code of RepeatNet to truncate some tensor's shape to `self.max_seq_length`, or preprocess another benchmark dataset into sequences no longer than 50.
