### ISSUE TITLE
处理Electronics_5数据，将其转化为原子文件是报错

### ISSUE THREAD

**Issue by yztian1997** [RUCAIBox/RecBole#1223]
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    datasets.convert_item()
  File "D:\大数据与人工智能\lightgcn\RecSysDatasets-master\conversion_tools\src\extended_dataset.py", line 3948, in convert_item
    input_item_data = self.load_item_data()
  File "D:\大数据与人工智能\lightgcn\RecSysDatasets-master\conversion_tools\src\extended_dataset.py", line 3919, in load_item_data
    finished_data = origin_data.drop(columns=['salesRank', 'categories'])
  File "D:\Anaconda3\envs\pytorch-gpu\lib\site-packages\pandas\core\frame.py", line 4308, in drop
    return super().drop(
  File "D:\Anaconda3\envs\pytorch-gpu\lib\site-packages\pandas\core\generic.py", line 4153, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "D:\Anaconda3\envs\pytorch-gpu\lib\site-packages\pandas\core\generic.py", line 4188, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "D:\Anaconda3\envs\pytorch-gpu\lib\site-packages\pandas\core\indexes\base.py", line 5592, in drop
    raise KeyError(f"{labels[mask]} not found in axis")
KeyError: "['salesRank' 'categories'] not found in axis"

应该怎么解决

**Comment by hyp1231** [comment]
请参考 #1233 。
