### ISSUE TITLE
Making my own data to atomic files. (+ CTR negative samplingg with CEloss question)

### ISSUE THREAD

**Issue by Yoloniverse** [RUCAIBox/RecBole#1239]
I have tried to makde my own data to atomic files.

So this is what it looks like. 
![스크린샷, 2022-04-07 12-08-22](https://user-images.githubusercontent.com/89169051/162112480-9bc3c810-52ca-4371-a62d-b8d958d9b358.png)

As you can see, one column called 'user_emb' is a vector. I made as Recbole suggested as float_seq. Then I tried to create the data
with following code

```
import argparse
from recbole.quick_start import run_recbole
import logging
from logging import getLogger
import torch
import pickle
import recbole
from recbole.config import Config
from recbole.data import create_dataset, data_preparation, save_split_dataloaders, load_split_dataloaders, create_samplers
from recbole.utils import init_logger, get_model, get_trainer, init_seed, set_color
recbole.__file__

config_dict = {
                'field_separator' : ',',
                'seq_separator' : ' ',
                'neg_sampling' : {'uniform': 1}, 
                'data_path': 'run_example/dataset/',
               'load_col':
                   {'inter': ['user_id', 'item_id', 'timestamp'], ##'rating'
                    'item': ['item_id','difficulty', 'answeringType', 'item_embedding'],
                    'user': ['user_id', 'age', 'interest', 'bfCEFR', 'afCEFR', 'user_embedding']},
                   'USER_ID_FIELD': 'user_id',
                   'ITEM_ID_FIELD': 'item_id',
                   'TIME_FIELD': 'timestamp',
                    'save_dataset': True,
                    'save_dataloaders': True,

                    ##training
                    'epochs':1,
                    'train_batch_size': 1024,
                    'learner':'adam',
                    'learning_rate': 0.0001,
                    
                    'eval_step': 1,
                    'stopping_step':10, ##early-stopping
                    'clip_grad_norm': {'max_norm':1},
                    'loss_decimal_place': 5,
                    'weight_decay': 0.0001,
                    'require_pow': False,
                    
                    ##evaluation
                    'eval_args': {'group_by': 'user', 'order':'TO', 'split': {'RS': [0.8, 0.1, 0.1]}, 'mode':'uni10'},
                    'metrics': ['AUC', 'Logloss'],

                    'valid_metric': 'AUC', #['Hit@10', 'NDCG@10'],
                    'eval_batch_size': 1024,
                    'metric_decimal_place': 5,
                   }
                   



# configurations initialization
config = Config(model='DeepFM', dataset = 'CIP', config_dict= config_dict) ##, config_file_list=config_file_list, config_dict=config_dict)


init_seed(config['seed'], config['reproducibility'])
# logger initialization
init_logger(config)
logger = getLogger()
logger.info(config)

# dataset filtering
dataset = create_dataset(config)
```
**The data is created but when I check dataset.user_feat, I do not see the 'user_emb'. I did not get any error for data creation though. Why is the 'user_emb' gone? Can you tell me why it is gone and how I can have it back as it should?**
![스크린샷, 2022-04-07 12-13-46](https://user-images.githubusercontent.com/89169051/162112986-9b7750b6-7faa-4334-9414-4680582028be.png)

You mentioned in a different question earlier about 'Load Pre-trained Embedding'. I have not tried this one (I guess it should work), but I wish not to make different files if not must. So if possible, I wanna put user_emb in user_feat with data.user file.

And my data is CTR prediction-like-data so I dont have explicit label data. So I wanna make negative samples by negative_sampling config. But CEloss gives me warning. Yet, I thought I could just do binary CEloss but it is already pre-blocked by the warning. 
**So in CTR case, must I use BPRloss? If not, how can I do binary classification with CTR data with negative_sampling and CE or CE-like loss?**

**Comment by Yoloniverse** [comment]
I've tried Load Pre-trained Embedding as well but I got an error.
The error shows this.
```
07 Apr 15:36    WARNING  No columns has been loaded from [useremb]
07 Apr 15:36    WARNING  No columns has been loaded from [itememb]
Traceback (most recent call last):

  File "/tmp/ipykernel_68576/3787465130.py", line 99, in <module>
    dataset = create_dataset(config)

  File "/home/hojun/Python/Models/Recommender_systems/RecBole/recbole/data/utils.py", line 68, in create_dataset
    dataset = dataset_class(config)

  File "/home/hojun/Python/Models/Recommender_systems/RecBole/recbole/data/dataset/dataset.py", line 103, in __init__
    self._from_scratch() ##load dataset from scratch

  File "/home/hojun/Python/Models/Recommender_systems/RecBole/recbole/data/dataset/dataset.py", line 115, in _from_scratch
    self._data_processing()

  File "/home/hojun/Python/Models/Recommender_systems/RecBole/recbole/data/dataset/dataset.py", line 160, in _data_processing
    self._remap_ID_all()

  File "/home/hojun/Python/Models/Recommender_systems/RecBole/recbole/data/dataset/dataset.py", line 956, in _remap_ID_all
    remap_list = self._get_remap_list(alias)

  File "/home/hojun/Python/Models/Recommender_systems/RecBole/recbole/data/dataset/dataset.py", line 946, in _get_remap_list
    ftype = self.field2type[field]

KeyError: 'uid'
```
And below is the code I implemented.

```
import logging
from logging import getLogger
import torch
import pickle
import recbole
from recbole.config import Config
from recbole.data import create_dataset, data_preparation, save_split_dataloaders, load_split_dataloaders, create_samplers
from recbole.utils import init_logger, get_model, get_trainer, init_seed, set_color
recbole.__file__

config_dict = {
                'field_separator' : ',',
                'seq_separator' : ' ',
                'neg_sampling' : {'uniform': 1}, 
                'data_path': '/dataset/',
               'load_col':
                   {'inter': ['user_id', 'item_id', 'timestamp'],
                    'item': ['item_id','difficulty', 'answeringType', 'item_embedding'],
                    'user': ['user_id', 'age', 'interest', 'bfCEFR', 'afCEFR', 'user_embedding']},
                    'additional_feat_suffix': ['useremb', 'itememb'],
                    'useremb': ['uid', 'user_emb'],
                    'itememb': ['iid', 'item_emb'],
                    'alias_of_user_id': ['uid'],
                    'alias_of_item_id': ['iid'],
                    'preload_weight': {'uid': 'user_emb', 'iid':'item_emb'},
                   'USER_ID_FIELD': 'user_id',
                   'ITEM_ID_FIELD': 'item_id',
                   'TIME_FIELD': 'timestamp',

                    'save_dataset': True,
                    'save_dataloaders': True,

                    ##training
                    'epochs':1,
                    'train_batch_size': 1024,
                    'learner':'adam',
                    'learning_rate': 0.0001,
                    # 'neg_sampling':{'uniform': 1, 'dynamic':3},
                    'eval_step': 1,
                    'stopping_step':10, ##early-stopping
                    'clip_grad_norm': {'max_norm':1},
                    'loss_decimal_place': 5,
                    'weight_decay': 0.0001,
                    'require_pow': False,
                    
                    ##evaluation
                    'eval_args': {'group_by': 'user', 'order':'TO', 'split': {'RS': [0.8, 0.1, 0.1]}, 'mode':'uni10'},
                    'metrics': ['AUC', 'Logloss'],
                    'valid_metric': 'AUC', #['Hit@10', 'NDCG@10'],
                    'eval_batch_size': 1024,
                    'metric_decimal_place': 5,
                   }



# configurations initialization
config = Config(model='DeepFM', dataset = 'CIP', config_dict= config_dict) ##, config_file_list=config_file_list, config_dict=config_dict)


init_seed(config['seed'], config['reproducibility'])
# logger initialization
init_logger(config)
logger = getLogger()
logger.info(config)

# dataset filtering
dataset = create_dataset(config)
```

Can you point out where I was wrong about this? I thought I did follow the instruction.
Below I am providing snippets of my atomic files.

.itememb
![스크린샷, 2022-04-07 15-45-23](https://user-images.githubusercontent.com/89169051/162136797-c1365444-4ee6-4b5a-ab3c-071fe387409b.png)
.useremb
![스크린샷, 2022-04-07 15-46-00](https://user-images.githubusercontent.com/89169051/162136868-fb304883-9484-417a-b7ff-5819f7fa21c9.png)
.inter
![스크린샷, 2022-04-07 15-46-47](https://user-images.githubusercontent.com/89169051/162136991-0f5975a1-3f5e-449c-8664-515a392d0cf7.png)
.item
![스크린샷, 2022-04-07 15-47-25](https://user-images.githubusercontent.com/89169051/162137095-9cd2cae2-6f1b-4b73-b77b-c95762557ff9.png)
.user
![스크린샷, 2022-04-07 15-48-25](https://user-images.githubusercontent.com/89169051/162137242-c87e45ea-ba1f-45cc-af48-e887f71a25aa.png)

**Comment by leoleojie** [comment]
@Yoloniverse Thanks for your attention for RecBole!
1、On your first try，you want to load user_emb, item_emb from .user, .item files. While in your config dict, you set 
```
'load_col':
                   {'inter': ['user_id', 'item_id', 'timestamp'], ##'rating'
                    'item': ['item_id','difficulty', 'answeringType', 'item_embedding'],
                    'user': ['user_id', 'age', 'interest', 'bfCEFR', 'afCEFR', 'user_embedding']},
```
that should be
```
'load_col':
                   {'inter': ['user_id', 'item_id', 'timestamp'], ##'rating'
                    'item': ['item_id','difficulty', 'answeringType', 'item_emb'],
                    'user': ['user_id', 'age', 'interest', 'bfCEFR', 'afCEFR', 'user_emb']},
```
2、If you want to use negative sampling in the cross entropy loss, you can use BCE as the loss function in the pair-wise way 
3、 In load Pre-trained Embedding, you set config as:
```
'load_col':
                   {'inter': ['user_id', 'item_id', 'timestamp'],
                    'item': ['item_id','difficulty', 'answeringType', 'item_embedding'],
                    'user': ['user_id', 'age', 'interest', 'bfCEFR', 'afCEFR', 'user_embedding']},
                    'additional_feat_suffix': ['useremb', 'itememb'],
                    'useremb': ['uid', 'user_emb'],
                    'itememb': ['iid', 'item_emb'],
```
But ``` 'useremb': ['uid', 'user_emb'],
                    'itememb': ['iid', 'item_emb'],``` should in ```'load_col'```. Only in this way can we load data from these files.
So it should be
```
'load_col':
        {'inter': ['user_id', 'item_id', 'timestamp'],
         'item': ['item_id', 'difficulty', 'answeringType', 'item_embedding'],
         'user': ['user_id', 'age', 'interest', 'bfCEFR', 'afCEFR', 'user_embedding'],
         'useremb': ['uid','user_emb'],
        'itememb': ['iid','item_emb']},
```

**Comment by Jeriousman** [comment]
Thank you for your advice. Thanks to you I have managed to put the useremb_feat and itememb_feat with my first approach (putting emb data into .user and .item)


When I see interaction, it is as below. I can see item_emb and user_emb got into the interaction as well.
```
interaction
Out[39]: 
The batch_size of interaction: 2048
    user_id, torch.Size([2048]), cpu, torch.int64
    item_id, torch.Size([2048]), cpu, torch.int64
    age, torch.Size([2048]), cpu, torch.int64
    interest, torch.Size([2048]), cpu, torch.int64
    bfCEFR, torch.Size([2048]), cpu, torch.int64
    afCEFR, torch.Size([2048]), cpu, torch.int64
    user_emb, torch.Size([2048, 300]), cpu, torch.float32
    answeringType, torch.Size([2048]), cpu, torch.int64
    difficulty, torch.Size([2048]), cpu, torch.int64
    item_emb, torch.Size([2048, 300]), cpu, torch.float32
    label, torch.Size([2048]), cpu, torch.float32
```
With this, I tried to train as usual with code below,

```
init_seed(config['seed'], config['reproducibility'])
model = get_model(config['model'])(config, train_data.dataset).to(config['device'])
logger.info(model)

# trainer loading and initialization
trainer = get_trainer(config['MODEL_TYPE'], config['model'])(config, model)

# model training
best_valid_score, best_valid_result = trainer.fit(
    train_data, valid_data, saved=True, show_progress=config['show_progress']
)

# model evaluation
test_result = trainer.evaluate(test_data, load_best_model=True, show_progress=config['show_progress'])

logger.info(set_color('best valid ', 'yellow') + f': {best_valid_result}')
logger.info(set_color('test result', 'yellow') + f': {test_result}')
```

Then it shows me an error : 
```
Traceback (most recent call last):

  File "/tmp/ipykernel_17244/1897559203.py", line 204, in <module>
    train_data, valid_data, saved=True, show_progress=config['show_progress']

  File "/home/hojun/Python/Models/Recommender_systems/RecBole/recbole/trainer/trainer.py", line 335, in fit
    train_loss = self._train_epoch(train_data, epoch_idx, show_progress=show_progress)

  File "/home/hojun/Python/Models/Recommender_systems/RecBole/recbole/trainer/trainer.py", line 181, in _train_epoch
    losses = loss_func(interaction)

  File "/home/hojun/Python/Models/Recommender_systems/RecBole/recbole/model/context_aware_recommender/deepfm.py", line 69, in calculate_loss
    output = self.forward(interaction)

  File "/home/hojun/Python/Models/Recommender_systems/RecBole/recbole/model/context_aware_recommender/deepfm.py", line 63, in forward
    y_deep = self.deep_predict_layer(self.mlp_layers(deepfm_all_embeddings.view(batch_size, -1)))

  File "/home/hojun/anaconda3/envs/recbole/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)

  File "/home/hojun/Python/Models/Recommender_systems/RecBole/recbole/model/layers.py", line 85, in forward
    return self.mlp_layers(input_feature)

  File "/home/hojun/anaconda3/envs/recbole/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)

  File "/home/hojun/anaconda3/envs/recbole/lib/python3.7/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)

  File "/home/hojun/anaconda3/envs/recbole/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)

  File "/home/hojun/anaconda3/envs/recbole/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2048x6080 and 100x128)
```
I guess it is because of the item_emb and user_emb, which have different dimension values came in. From Load Pre-trained Embedding in your documentation, I guess I have to manually deal with this embedding data in models myself? Am I right? And then after all the process, should it be a single dimension like other features?

+question, just like in Pre-trained Embedding in your documentation, I may have to take out the emb independently (my approach 2 which made independent useremb, itememb files) and manually work in model part by myself (not putting emb data into interaction because of dimension mismatch)?

**Comment by leoleojie** [comment]
I think this is because you pass ```user_emb``` and ```item_emb``` to another embedding layer. As you can see, in deepfm.py, 
```    def forward(self, interaction):
        deepfm_all_embeddings = self.concat_embed_input_fields(interaction)
```
it pass interaction into ```self.concat_embed_input_fields```, which embed the feature. 
In this case, for example, user_emb(batch_size, embedding_size) will be (batch_size, embedding_size, embedding_size), which made a mistake.
So if you want to use use_emb, item_emb as your first approach, I think you should concatenate it with other features' embedding(output of ```self.concat_embed_input_fields(interaction)```).   And modify MLP parameters(input size).
By the way, if use your first approach, user_emb and item_emb are just features, they will not be optimized. 
So you'd better use Pre-trained Embedding in out documentation. And you should manually set embedding in model part like ``` self.user_embedding = nn.Embedding.from_pretrained(torch.from_numpy(pretrained_user_emb))``` . You can refer to our [document](https://recbole.io/docs/user_guide/usage/load_pretrained_embedding.html) for more details.

**Comment by Jeriousman** [comment]
I appreciate your advice much @leoleojie. I will try some of the tricks and report if anything!
