### ISSUE TITLE
[🐛BUG] epinions数据集预处理问题

### ISSUE THREAD

**Issue by kuzma-long** [RUCAIBox/RecBole#1270]
Traceback (most recent call last):
  File "main.py", line 128, in <module>
    run_single_model(args)
  File "main.py", line 52, in run_single_model
    dataset = create_dataset(config)
  File "/home/chaolong/.conda/envs/recbole/lib/python3.8/site-packages/recbole/data/utils.py", line 68, in create_dataset
    dataset = dataset_class(config)
  File "/home/chaolong/.conda/envs/recbole/lib/python3.8/site-packages/recbole/data/dataset/sequential_dataset.py", line 36, in __init__
    super().__init__(config)
  File "/home/chaolong/.conda/envs/recbole/lib/python3.8/site-packages/recbole/data/dataset/dataset.py", line 96, in __init__
    self._from_scratch()
  File "/home/chaolong/.conda/envs/recbole/lib/python3.8/site-packages/recbole/data/dataset/dataset.py", line 108, in _from_scratch
    self._data_processing()
  File "/home/chaolong/.conda/envs/recbole/lib/python3.8/site-packages/recbole/data/dataset/dataset.py", line 151, in _data_processing
    self._data_filtering()
  File "/home/chaolong/.conda/envs/recbole/lib/python3.8/site-packages/recbole/data/dataset/dataset.py", line 178, in _data_filtering
    self._reset_index()
  File "/home/chaolong/.conda/envs/recbole/lib/python3.8/site-packages/recbole/data/dataset/dataset.py", line 828, in _reset_index
    raise ValueError('Some feat is empty, please check the filtering settings.')
ValueError: Some feat is empty, please check the filtering settings.
在使用epinions数据集跑sasrec模型时，报如上错误，感觉是数据集不干净，但recbole应该有处理这些缺失值的代码吧，为啥这里直接报错呢，我该如何解决。

数据集配置如下：
# Atomic File Format
field_separator: "\t"
seq_separator: " "

# Common Features
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating
TIME_FIELD: timestamp
seq_len: ~
# Label for Point-wise DataLoader
LABEL_FIELD: rating
# NegSample Prefix for Pair-wise DataLoader
NEG_PREFIX: neg_
# Sequential Model Needed
ITEM_LIST_LENGTH_FIELD: item_length
LIST_SUFFIX: _list
MAX_ITEM_LIST_LENGTH: 50
POSITION_FIELD: position_id
# Knowledge-based Model Needed
HEAD_ENTITY_ID_FIELD: head_id
TAIL_ENTITY_ID_FIELD: tail_id
RELATION_ID_FIELD: relation_id
ENTITY_ID_FIELD: entity_id

# Selectively Loading
load_col:
  inter: [user_id,item_id,timestamp]
unload_col: ~
unused_col: ~

# Filtering
rm_dup_inter: ~
val_interval: ~
filter_inter_by_user_or_item: True
user_inter_num_interval: '[5,inf)'
item_inter_num_interval: '[5,inf)'

# Preprocessing
alias_of_user_id: ~
alias_of_item_id: ~
alias_of_entity_id: ~
alias_of_relation_id: ~
preload_weight: ~
normalize_field: ~
normalize_all: True

**Comment by hyp1231** [comment]
你好，这个不是因为数据有缺失值，而是因为 epinion 数据集特别稀疏，在 5-core 筛选后就没有交互记录了。

建议修改下述配置至合理值：
```yaml
user_inter_num_interval: '[5,inf)'
item_inter_num_interval: '[5,inf)'
```
