### ISSUE TITLE
Automatically get token2id for users

### ISSUE THREAD

**Issue by giuspillo** [RUCAIBox/RecBole#1307]
Hi! I'm here again!

I'm using this script to get predictions and scores for all my users; these users have tokens (as ids) from 0 to 6039 except for 4 numbers, so I cretated a list and removed those 4 tokens.
In this way, the script works with no problem.

But I have other datasets using several and very sparse tokens as ids, so this solution won't work. Is there any way to automatically obtain all the tokens so that they are converted into the internal ids (similarly to what happens with items)?

Here is my script

    parser = argparse.ArgumentParser()
    parser.add_argument('--pth_file', '-p', type=str, default=None, help='name of .pth file to load')
    parser.add_argument('--topk', '-k', type=str, default='5', help='get top k predictions')
    args, _ = parser.parse_known_args()

    pthfile = args.pth_file
    topk = int(args.topk)

    config, model, dataset, train_data, valid_data, test_data = load_data_and_model(
        model_file='drive/MyDrive/RecBole/'+pthfile,
    )  

    uid_series = np.arange(1, test_data.dataset.user_num)

    # external user ids converted to internal
    users = [str(i) for i in range(0,6040)]
    users.remove('3597')
    users.remove('4348')
    users.remove('4485')
    users.remove('5849')
    uid_series = dataset.token2id(dataset.uid_field, users )
    scores, int_ids_items = full_sort_topk(uid_series, model, test_data, k=topk, device=config['device'])

    # internal item ids converted to external
    ext_ids_items = dataset.id2token(dataset.iid_field, int_ids_items.cpu())

    print('\n\nUid_series:')
    print(uid_series)
    print('\n\nTop5 items:')
    print(ext_ids_items)

In addition, i wanted to know if it is possible to use

    benchmark_filename: ['part1', 'part2', 'part3']
    
with only train set (part1) and test set (part3), so without using a validation set, and in such case if it is necessary to set some properties in someway.

Thank you!

**Comment by leoleojie** [comment]
@giuspillo Hello, thanks for your attention to RecBole!
1. You can use `dataset.field2token_id` to get all the tokens and their relevant internal ids.
2. If you don't want to use valid set,  just do not pass in `valid_data` to `trainer`. And in this case,  the early_stopping is invalid.

**Comment by giuspillo** [comment]
Thank you!

1. solved!
2. how the config file would be in such case?

**Comment by giuspillo** [comment]
Got it, I'll try and keep you updated.
Thank you very much!

**Comment by giuspillo** [comment]
Update: I'm experiencing a problem with the splitting and the model KGAT.

As required, I have the file of interaction random split into part1.inter, part2.inter, part3.inter (just to check the correctness of the execution), then the files .link and .kg. Of course, I have the whole dataset (not split into 3 parts) on a file .inter too.

When using KGAT as recommendation model, providing the model the whole dataset, everything works correctly; but when I try to use the split files, I got the following error:

Traceback (most recent call last):
  File "drive/MyDrive/RecBole/run_recbole.py", line 28, in <module>
    run_recbole(model=args.model, dataset=args.dataset, config_file_list=config_file_list)
  File "/content/drive/MyDrive/RecBole/recbole/quick_start/quick_start.py", line 41, in run_recbole
    dataset = create_dataset(config)
  File "/content/drive/MyDrive/RecBole/recbole/data/utils.py", line 68, in create_dataset
    dataset = dataset_class(config)
  File "/content/drive/MyDrive/RecBole/recbole/data/dataset/kg_dataset.py", line 67, in __init__
    super().__init__(config)
  File "/content/drive/MyDrive/RecBole/recbole/data/dataset/dataset.py", line 96, in __init__
    self._from_scratch()
  File "/content/drive/MyDrive/RecBole/recbole/data/dataset/dataset.py", line 108, in _from_scratch
    self._data_processing()
  File "/content/drive/MyDrive/RecBole/recbole/data/dataset/dataset.py", line 153, in _data_processing
    self._remap_ID_all()
  File "/content/drive/MyDrive/RecBole/recbole/data/dataset/kg_dataset.py", line 264, in _remap_ID_all
    self._merge_item_and_entity()
  File "/content/drive/MyDrive/RecBole/recbole/data/dataset/kg_dataset.py", line 251, in _merge_item_and_entity
    entity_id_map[i] = new_item_token2id[self.entity2item[entity_token[i]]]
KeyError: '9251'

In this situation, the token '9251' is a property that of course does not appear in the .inter file (since it is nor user or item); the same happens for items for which there are no interactions, but only properties are available.

Why the system behaves in these two different manners, given those settings?

**Comment by leoleojie** [comment]
In this case, do at least part of  parts 1, 2 and 3 contains '9521'?  If so, have you entered part1, part2, and part3 as benchmarks files ?

**Comment by giuspillo** [comment]
Hi, the answer is no. I understood that part1, part2 and part3 must contain only interaction information (a subset of the  .inter file, but split in 3 parts), so user-item information (1/0); '9521' is related to a property in the .kg file, not to a rating, so it only appears in the knowledge source.

**Comment by leoleojie** [comment]
As you can see, at here we just merge item-id and entity-id into the same id-space. If '9521' is a property in the .kg file and not item-id or its related entity-id, perhaps you set some parameters wrong. Could you please provide the parameters you set and the format description of the dataset?

**Comment by Sherry-XLL** [comment]
Hello @giuspillo, we have released the [1.1.1 version of RecBole](https://github.com/RUCAIBox/RecBole/releases/tag/v1.1.1) on Oct 5 2022, and we update the pre-processing procedure of knowledge graph now. The suggestions and feedback from open source users are our driving force for continuous updating. We welcome you very much to use our library again and give your valuable comments.

Closing due to inactivity. Please open a new issue if you're still having questions.
