### ISSUE TITLE
IndexError: index out of range in self

### ISSUE THREAD

**Issue by ajster1** [RUCAIBox/RecBole#1318]
I'm getting a torch error when using a custom data set (train/valid/test).  It works when my script removes all sessions that don't have at least two 2 items (including label), but when I increase to 3+ items it fails with the below error. I'm using NARM but the same happens with GRU4Rec as well.

```
Traceback (most recent call last):
  File "C:\projects\sbr\lmtrain.py", line 64, in <module>
    best_valid_score, best_valid_result = trainer.fit(
  File "C:\Users\AJ\AppData\Local\Programs\Python\Python39\lib\site-packages\recbole\trainer\trainer.py", line 337, in fit
    train_loss = self._train_epoch(train_data, epoch_idx, show_progress=show_progress)
  File "C:\Users\AJ\AppData\Local\Programs\Python\Python39\lib\site-packages\recbole\trainer\trainer.py", line 182, in _train_epoch
    losses = loss_func(interaction)
  File "C:\Users\AJ\AppData\Local\Programs\Python\Python39\lib\site-packages\recbole\model\sequential_recommender\narm.py", line 99, in calculate_loss
    seq_output = self.forward(item_seq, item_seq_len)
  File "C:\Users\AJ\AppData\Local\Programs\Python\Python39\lib\site-packages\recbole\model\sequential_recommender\narm.py", line 77, in forward
    item_seq_emb = self.item_embedding(item_seq)
  File "C:\Users\AJ\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\AJ\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\sparse.py", line 158, in forward
    return F.embedding(
  File "C:\Users\AJ\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\functional.py", line 2183, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
IndexError: index out of range in self
```

I traced the RecBole code and _item_seq_ does include items that are larger than allowed by `nn.Embedding(self.n_items, self.embedding_size, padding_idx=0)`.  A number of the items are larger than _self.n_items_.  When these numbers included in  _item_seq_ are fed to the below line of code, the error is triggered in torch.

`item_seq_emb = self.item_embedding(item_seq)`

My unique sessions/users counts match what is displayed during training but the unique items count does not match.  Interestingly the unique item count also does not match when I limit sessions to at least two 2 items, but it does train successfully. The RecBole number is always lower. Is additional filtering taking place to reduce the items number?

```
Preprocessing stats:
Unique Items 6906
Unique Sessions 1947
```

```
The number of users: 1948
Average actions of users: 7.824345146379045
The number of items: 6654
Average actions of items: 2.289794077859612
The number of inters: 15234
The sparsity of the dataset: 99.88247176822821%
```

Data is saved in this format.  The error occurs if I use the _item_length_ field or not.

```
user_id:token	item_id_list:token_seq	item_id:token	item_length:token
265	3641 3642 3643 3644 3645 5527 5590	3640	7
7261	3465 3467 3468 3469 3470 3471 3472 3473 3474 3475 3476 5527	3466	12
8726	400 404 405 406 407 408 409 410 411 412 413 414 415 416 417 418 419 420 421 422 5527	399	21
17634	5994 7010 7135	7322	3
16841	6 5435 5436 5437 5438 5440 5441 5442 5443 5444 5446 5451 5527 6216 6708	5433	15
19766	1078 1079 1080 1081 1082 1083 1085 1086 5527	1076	9
9674	4205 4206 4207 4208 4209 5527	4204	6
18865	9 7501	7502	2
20149	5867 7437 7441	7502	3
15793	7311 7501 7527	7522	3
```

Configuration:

```
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = dataset/lm_sess
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 10
train_batch_size = 2048
learner = adam
learning_rate = 0.001
neg_sampling = None
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'LS': 'valid_and_test'}, 'order': 'TO', 'mode': 'full', 'leave_one_num': 2, 'group_by': 'user'}
repeatable = True
metrics = ['Recall', 'MRR', 'NDCG', 'MAP', 'Hit', 'Precision', 'AveragePopularity', 'ItemCoverage']
topk = [5]
valid_metric = MRR@5
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id_list', 'item_id']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = [0,inf)
item_inter_num_interval = [0,inf)
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = None
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
benchmark_filename = ['train', 'valid', 'test']

Other Hyper Parameters:
wandb_project = recbole
require_pow = False
embedding_size = 64
hidden_size = 128
n_layers = 1
dropout_probs = [0.25, 0.5]
loss_type = CE
MODEL_TYPE = ModelType.SEQUENTIAL
leave_one_num = 2
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
device = cpu
train_neg_sample_args = {'strategy': 'none'}
eval_neg_sample_args = {'strategy': 'full', 'distribution': 'uniform'}
```

Using:
Python v3.9.7
torch v1.11.0
RecBole v1.0.1

As a side note if I load the data in this format/configuration which lets RecBole do the split, it does work.

`'eval_args': {'split': {'RS': [8, 1, 1]}, 'order': 'TO', 'mode': 'full', 'leave_one_num': 2},`

```
session_id:token	item_id:token	timestamp:float
0	19318	1654178766
1	24993	1652712846
2	17335	1652831141
3	17215	1653507732
```

**Comment by ajster1** [comment]
I created a dummy dataset and was able to reproduce the error with the same configuration.

```
Train:
user_id:token	item_id_list:token_seq	item_id:token	item_length:token
0	0 1 2 3 4	9	5

Valid:
user_id:token	item_id_list:token_seq	item_id:token	item_length:token
1	0 1 2 3	5	4

Test:
user_id:token	item_id_list:token_seq	item_id:token	item_length:token
2	0 1 2 3	4	4
```

Which translates to the below dict in _self.field2id_token_:

`{'user_id': array(['[PAD]', '0', '1', '2'], dtype='<U5'), 'item_id': array(['[PAD]', '9', '5', '4'], dtype='<U5'), 'item_id_list': array(['[PAD]', '0', '1', '2', '3', '4'], dtype='<U5')}
`

The _NARM_ class then initializes _self.item_embedding_ using _self.n_items_, which is set in the _SequentialRecommender_ class using _self.n_items = dataset.num(self.ITEM_ID)_, which is set to **4** by _self.field2id_token[field]_ in the _Dataset_ class. **4** is the length of the _item_id_ field, including padding.

`self.item_embedding = nn.Embedding(self.n_items, self.embedding_size, padding_idx=0)`

When the _forward_ method is called for training with the below parameters the _item_seq_ tensor is to big for: Embedding(4, 64, padding_idx=0)

```
item_seq:
tensor([[1, 2, 3, 4, 5]])

item_seq_len:
tensor([5])
```
Hopefully this should help with understanding the problem I am running into.

**Comment by Wicknight** [comment]
@ajster1 Hello, sorry for the late reply.
For this problem, I think it is caused by the fact that the feature **'item_id_list'** and feature **'item_id'** are not mapped to the same ID system. You can add the items contained in the **'item_id_list'** to the ID mapping system through parameter **'alias_of_item_id (list)'**. You can refer to our documentation about this [parameter](https://recbole.io/docs/user_guide/config/data_settings.html#preprocessing). An example is as follows：
`
alias_of_item_id: ['item_id_list']
`

**Comment by ajster1** [comment]
That looks to have fixed the problem for both.  Thanks!
