### ISSUE TITLE
自动调参运行run_hyper.py报错

### ISSUE THREAD

**Issue by LimQueen** [RUCAIBox/RecBole#1320]
您好！
麻烦请问一下：
我想运行run_hyper.py实现自动调参时，运行这段代码：python run_hyper.py  --model=NARM --dataset=ml-100k --params_file=hyper.test
在hp.run()处报了AttributeError: 'numpy.random.mtrand.RandomState' object has no attribute 'integers'的错，具体报错内容如下。
================================================================================
ERROR in rec_eval
EXCEPTION
<class 'AttributeError'>
'numpy.random.mtrand.RandomState' object has no attribute 'integers'
NODE
0 randint
1   Literal{3}
2  size =
3   len
4     array_union
5       array_union
6         array_union
7           Literal{new_ids}
8  rng =
9   Literal{rng-placeholder}
================================================================================
  0%|                                                                                                                        | 0/90 [00:00<?, ?trial/s, best loss=?] 
Traceback (most recent call last):
  File "run_hyper.py", line 36, in <module>
    main()
  File "run_hyper.py", line 28, in main
    hp.run()
  File "D:\Desktop\RecBole-master-prev\recbole\trainer\hyper_tuning.py", line 309, in run
    fmin(self.trial, self.space, algo=self.algo, max_evals=self.max_evals)
  File "D:\Downloads\Anaconda\lib\site-packages\hyperopt\fmin.py", line 586, in fmin
    rval.exhaust()
  File "D:\Downloads\Anaconda\lib\site-packages\hyperopt\fmin.py", line 364, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.asynchronous)
  File "D:\Downloads\Anaconda\lib\site-packages\hyperopt\fmin.py", line 278, in run
    new_trials = algo(
  File "D:\Desktop\RecBole-master-prev\recbole\trainer\hyper_tuning.py", line 105, in exhaustive_search
    idxs, vals = pyll.rec_eval(domain.s_idxs_vals, memo={
  File "D:\Downloads\Anaconda\lib\site-packages\hyperopt\pyll\base.py", line 902, in rec_eval
    rval = scope._impls[node.name](*args, **kwargs)
  File "D:\Downloads\Anaconda\lib\site-packages\hyperopt\pyll\stochastic.py", line 100, in randint
    return rng.integers(low, high, size)
AttributeError: 'numpy.random.mtrand.RandomState' object has no attribute 'integers'

想请问如何修改呢？很抱歉打扰一下你们。谢谢！
祝生活愉快！

**Comment by chenyuwuxin** [comment]
@LimQueen 感谢您的关注！
这个问题是由于hyperopt包的版本与numpy不匹配，如果出现冲突，请尝试降低hyperopt的版本(例如降低到0.2.5)。

**Comment by LimQueen** [comment]
> 

谢谢您的回复！我再尝试一下，感谢感谢！！

**Comment by LimQueen** [comment]
> python run_hyper.py --model=NARM --dataset=ml-100k --params_file=hyper.test

不好意思，麻烦再打扰一下！ValueError: neg_sampling [{'uniform': 1}] should be None when the loss_type is CE.报错是什么原因呢，貌似是algo的问题。
================================================================================
ERROR in rec_eval
EXCEPTION
<class 'AttributeError'>
'numpy.random.mtrand.RandomState' object has no attribute 'integers'
NODE
0 randint
1   Literal{3}
2  size =
3   len
4     array_union
5       array_union
6         array_union
7           Literal{new_ids}
8  rng =
9   Literal{rng-placeholder}
================================================================================
  0%|                                                                                                                        | 0/90 [00:00<?, ?trial/s, best loss=?] 
Traceback (most recent call last):
  File "run_hyper.py", line 36, in <module>
    main()
  File "run_hyper.py", line 28, in main
    hp.run()
  File "D:\Desktop\RecBole-master-prev\recbole\trainer\hyper_tuning.py", line 309, in run
    fmin(self.trial, self.space, algo=self.algo, max_evals=self.max_evals)
  File "D:\Downloads\Anaconda\lib\site-packages\hyperopt\fmin.py", line 586, in fmin
    rval.exhaust()
  File "D:\Downloads\Anaconda\lib\site-packages\hyperopt\fmin.py", line 364, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.asynchronous)
  File "D:\Downloads\Anaconda\lib\site-packages\hyperopt\fmin.py", line 278, in run
    new_trials = algo(
    new_trials = algo(
    idxs, vals = pyll.rec_eval(domain.s_idxs_vals, memo={
  File "D:\Downloads\Anaconda\lib\site-packages\hyperopt\pyll\base.py", line 902, in rec_eval
    rval = scope._impls[node.name](*args, **kwargs)
  File "D:\Downloads\Anaconda\lib\site-packages\hyperopt\pyll\stochastic.py", line 100, in randint
    return rng.integers(low, high, size)
AttributeError: 'numpy.random.mtrand.RandomState' object has no attribute 'integers'
PS D:\Desktop\RecBole-master-prev> python run_hyper.py --model=NARM --dataset=ml-100k --params_file=hyper.test
running parameters:
{'dropout_prob': 0.5, 'hidden_size': 128, 'learning_rate': 0.005, 'num_layers': 1}
  0%|                                                                                                                        | 0/90 [00:00<?, ?trial/s, best loss=?]job exception: neg_sampling [{'uniform': 1}] should be None when the loss_type is CE.

  0%|                                                                                                                        | 0/90 [00:00<?, ?trial/s, best loss=?]
Traceback (most recent call last):
  File "run_hyper.py", line 36, in <module>
    main()
  File "run_hyper.py", line 28, in main
    hp.run()
  File "D:\Desktop\RecBole-master-prev\recbole\trainer\hyper_tuning.py", line 309, in run
    fmin(self.trial, self.space, algo=self.algo, max_evals=self.max_evals)
  File "D:\Downloads\Anaconda\lib\site-packages\hyperopt\fmin.py", line 553, in fmin
    rval.exhaust()
  File "D:\Downloads\Anaconda\lib\site-packages\hyperopt\fmin.py", line 356, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.asynchronous)
  File "D:\Downloads\Anaconda\lib\site-packages\hyperopt\fmin.py", line 292, in run
    self.serial_evaluate()
  File "D:\Downloads\Anaconda\lib\site-packages\hyperopt\fmin.py", line 170, in serial_evaluate
    result = self.domain.evaluate(spec, ctrl)
  File "D:\Downloads\Anaconda\lib\site-packages\hyperopt\base.py", line 907, in evaluate
    rval = self.fn(pyll_rval)
  File "D:\Desktop\RecBole-master-prev\recbole\trainer\hyper_tuning.py", line 280, in trial
    result_dict = self.objective_function(config_dict, self.fixed_config_file_list)
  File "D:\Desktop\RecBole-master-prev\recbole\quick_start\quick_start.py", line 83, in objective_function
    config = Config(config_dict=config_dict, config_file_list=config_file_list)
  File "D:\Desktop\RecBole-master-prev\recbole\config\configurator.py", line 78, in __init__
    self._set_default_parameters()
  File "D:\Desktop\RecBole-master-prev\recbole\config\configurator.py", line 280, in _set_default_parameters
    raise ValueError(f"neg_sampling [{self.final_config_dict['neg_sampling']}] should be None "
ValueError: neg_sampling [{'uniform': 1}] should be None when the loss_type is CE.

麻烦您了！！由于初次使用recbole，有点不太熟练TAT。

**Comment by chenyuwuxin** [comment]
@LimQueen 您好，这是由于当loss的类型为交叉熵损失时，训练的任务属于多分类任务，此时不需要对样本进行负采样，因此需要设置负采样模式为**None**。您只需要在配置的.yaml文件中添加设置：`neg_sampling: ~
`即可。

**Comment by LimQueen** [comment]
> @LimQueen 您好，这是由于当loss的类型为交叉熵损失时，训练的任务属于多分类任务，此时不需要对样本进行负采样，因此需要设置负采样模式为**None**。您只需要在配置的.yaml文件中添加设置：`neg_sampling: ~ `即可。

谢谢您的回复！感谢感谢！！

**Comment by LimQueen** [comment]
您好，再打扰您一下，麻烦请教一下修改数据集的问题。
请问如果想用sequence_recommonder模型，并且我引入了新数据集默认用户匿名（即无user_id，timestamp），数据集header为用户的历史匿名交互序列（session）和真实数据中用户下一次交互的产品(label)。请问我应该修改哪些文件来改变模型默认的header呢（模型默认数据集header貌似是user_id、item_id、rating和timestamp，我想引入的数据集header为session（数据类型为序列，如[112,134,2,3] ）和label），目前修改了sample.yaml、overall.yaml，但貌似依然不太对，请问应该如何修改能让header匹配呢。
抱歉抱歉，打扰您这么多次，非常感谢！！

**Comment by chenyuwuxin** [comment]
@LimQueen 一般情况下，您无需修改库默认配置文件(sample.yaml，overall.yaml)。
而根据你的需求需要创建一个yaml文件来指定数据的处理方式，并且使用命令行参数--config_files来指定创建的配置文件。特别地，在序列推荐场景下，您提供了处理好的session后，应该使用**benchmark_file**指定划分好的train, val and test dataset。数据部分的处理示例如下：
```
data_path: ['Your Path']
benchmark_filename: ['train', 'val', 'test']
ITEM_ID_FIELD: label

load_col:
    inter: [session, label]

```
更多的配置处理选项字段请参考文档：[DataSettings](https://recbole.io/docs/user_guide/config/data_settings.html)。
在指定的数据集文件中，您需要修改文件的header使其符合原子文件格式，具体处理方式请参考[原子文件](https://recbole.io/docs/user_guide/data/atomic_files.html)。

**Comment by LimQueen** [comment]
@chenyuwuxin 
您好，目前我运行python run_hyper.py --model=NARM --dataset=sequence-data --config_files=NARM.yaml --params_file=hyper.test

其中NARM.yaml设置如下：
data_path: 'dataset\'
benchmark_filename: ['train', 'val', 'test']
ITEM_ID_FIELD: label
neg_sampling: ~

load_col:
    inter: [session, label]

hyper.test文件设置如下：
learning_rate choice [0.01,0.005,0.001,0.0005]
hidden_size choice [64]
n_layers choice [1,2]
dropout_probs choice ['[0.25,0.5]','[0.2,0.2]']

但报错了，貌似没能读取我新加的数据集（数据集是inter原子文件，训练集、验证集、测试集均有且命名对应）：
running parameters:
{'dropout_probs': '[0.2,0.2]', 'hidden_size': 64, 'learning_rate': 0.005, 'n_layers': 2}
0%| | 0/16 [00:00<?, ?trial/s, best loss=?E
RROR:hyperopt.fmin:job exception: object of type 'NoneType' has no len()

0%| | 0/16 [00:00<?, ?trial/s, best loss=?]
Traceback (most recent call last):
File "run_hyper.py", line 36, in
main()
File "run_hyper.py", line 28, in main
hp.run()
File "D:\Desktop\RecBole-master\recbole\trainer\hyper_tuning.py", line 309, in run
fmin(self.trial, self.space, algo=self.algo, max_evals=self.max_evals)
File "D:\Downloads\Anaconda\lib\site-packages\hyperopt\fmin.py", line 553, in fmin
rval.exhaust()
File "D:\Downloads\Anaconda\lib\site-packages\hyperopt\fmin.py", line 356, in exhaust
self.run(self.max_evals - n_done, block_until_done=self.asynchronous)
File "D:\Downloads\Anaconda\lib\site-packages\hyperopt\fmin.py", line 292, in run
self.serial_evaluate()
File "D:\Downloads\Anaconda\lib\site-packages\hyperopt\fmin.py", line 170, in serial_evaluate
result = self.domain.evaluate(spec, ctrl)
File "D:\Downloads\Anaconda\lib\site-packages\hyperopt\base.py", line 907, in evaluate
rval = self.fn(pyll_rval)
File "D:\Desktop\RecBole-master\recbole\trainer\hyper_tuning.py", line 280, in trial
result_dict = self.objective_function(config_dict, self.fixed_config_file_list)
File "D:\Desktop\RecBole-master\recbole\quick_start\quick_start.py", line 86, in objective_function
dataset = create_dataset(config)
File "D:\Desktop\RecBole-master\recbole\data\utils.py", line 68, in create_dataset
dataset = dataset_class(config)
File "D:\Desktop\RecBole-master\recbole\data\dataset\sequential_dataset.py", line 36, in init
super().init(config)
File "D:\Desktop\RecBole-master\recbole\data\dataset\dataset.py", line 96, in init
self._from_scratch()
File "D:\Desktop\RecBole-master\recbole\data\dataset\dataset.py", line 106, in _from_scratch
self._load_data(self.dataset_name, self.dataset_path)
File "D:\Desktop\RecBole-master\recbole\data\dataset\dataset.py", line 247, in _load_data
self._load_inter_feat(token, dataset_path)
File "D:\Desktop\RecBole-master\recbole\data\dataset\dataset.py", line 282, in _load_inter_feat
sub_inter_lens.append(len(temp))
TypeError: object of type 'NoneType' has no len()

可以麻烦您帮忙看一下吗，谢谢！！

**Comment by chenyuwuxin** [comment]
@LimQueen 您好，您的需求有些特殊，为了和目前的框架适配，建议在数据集文件添加"user_id"列，数据全为0即可。然后将"label"改为"item_id"，"session"改为"item_id_list"。配置文件内容为：
```
data_path: Your Path
benchmark_filename: ['train', 'val', 'test']
neg_sampling: ~
load_col:
    inter: [user_id,item_id, item_id_list]
```
我测试此情况下运行是没有问题的，希望能够帮助到你。

**Comment by LimQueen** [comment]
@chenyuwuxin 
您好，抱歉再次打扰您，还是报错了TAT。我的训练集sequence-data.train.inter前十行是这样的：
user_id	item_id_list	item_id
0	11673  897  10000  4477	3468
0	11673  897  10000	4477
0	11673  897	10000
0	11673	1
0	11673	194
0	11673	897
0	11673	6273
0	10  4265	4759
0	10	4265
已知用户前几次交互序列（itesm_id_list），预测下一次交互产品（item_id）。

目前配置文件NARM.yaml为：
data_path: 'dataset'
benchmark_filename: ['train', 'val', 'test']
neg_sampling: ~
load_col:
    inter: [user_id, item_id_list, item_id]

# model config
embedding_size: 32

# training settings
epochs: 10 #训练的最大轮数
train_batch_size: 128 #训练的batch_size
learner: adam #使用的pytorch内置优化器
# evalution settings
metrics: ["Recall", "MRR","NDCG","Hit","Precision"] #评测标准
valid_metric: MRR@10 #选取哪个评测标准作为作为提前停止训练的标准
eval_batch_size: 128 #评测的batch_size

运行代码为
python run_hyper.py --model=NARM --dataset=sequence-data --config_files=NARM.yaml --params_file=hyper.test

报错内容为：
running parameters:
{'dropout_probs': '[0.25,0.5]', 'hidden_size': 64, 'learning_rate': 0.005, 'n_layers': 1}
  0%|                                                                                                                        | 0/16 [00:00<?, ?trial/s, best loss=?E 
RROR:hyperopt.fmin:job exception: not enough values to unpack (expected 2, got 1)

  0%|                                                                                                                        | 0/16 [00:00<?, ?trial/s, best loss=?] 
Traceback (most recent call last):
  File "run_hyper.py", line 36, in <module>
    main()
  File "run_hyper.py", line 28, in main
    hp.run()
  File "D:\Desktop\RecBole-master\recbole\trainer\hyper_tuning.py", line 309, in run
    fmin(self.trial, self.space, algo=self.algo, max_evals=self.max_evals)
  File "D:\Downloads\Anaconda\lib\site-packages\hyperopt\fmin.py", line 553, in fmin
    rval.exhaust()
  File "D:\Downloads\Anaconda\lib\site-packages\hyperopt\fmin.py", line 356, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.asynchronous)
  File "D:\Downloads\Anaconda\lib\site-packages\hyperopt\fmin.py", line 292, in run
    self.serial_evaluate()
  File "D:\Downloads\Anaconda\lib\site-packages\hyperopt\fmin.py", line 170, in serial_evaluate
    result = self.domain.evaluate(spec, ctrl)
  File "D:\Downloads\Anaconda\lib\site-packages\hyperopt\base.py", line 907, in evaluate
    rval = self.fn(pyll_rval)
  File "D:\Desktop\RecBole-master\recbole\trainer\hyper_tuning.py", line 280, in trial
    result_dict = self.objective_function(config_dict, self.fixed_config_file_list)
  File "D:\Desktop\RecBole-master\recbole\quick_start\quick_start.py", line 86, in objective_function
    dataset = create_dataset(config)
  File "D:\Desktop\RecBole-master\recbole\data\utils.py", line 68, in create_dataset
    dataset = dataset_class(config)
  File "D:\Desktop\RecBole-master\recbole\data\dataset\sequential_dataset.py", line 36, in __init__
    super().__init__(config)
  File "D:\Desktop\RecBole-master\recbole\data\dataset\dataset.py", line 96, in __init__
    self._from_scratch()
  File "D:\Desktop\RecBole-master\recbole\data\dataset\dataset.py", line 106, in _from_scratch
    self._load_data(self.dataset_name, self.dataset_path)
  File "D:\Desktop\RecBole-master\recbole\data\dataset\dataset.py", line 247, in _load_data
    self._load_inter_feat(token, dataset_path)
  File "D:\Desktop\RecBole-master\recbole\data\dataset\dataset.py", line 280, in _load_inter_feat
    temp = self._load_feat(file_path, FeatureSource.INTERACTION)
  File "D:\Desktop\RecBole-master\recbole\data\dataset\dataset.py", line 416, in _load_feat
    field, ftype = field_type.split(':')
ValueError: not enough values to unpack (expected 2, got 1)

实在是不好意思，麻烦您再帮忙看一下，感谢感谢！！

**Comment by LimQueen** [comment]
@chenyuwuxin 
您好，我按照以下修改好原子文件后（以train为例），还是报了刚刚那个错QAQ：
import pandas as pd
df = pd.read_csv(r'dataset/beauty-session/beauty-session.train.inter', sep='\t')
df = df.rename(columns={'user_id:token':'user_id:token', 'item_id_list:token_seq':'item_id_list:token_seq', 'item_id:token':'item_id:token'})
df.to_csv(r'dataset/beauty-session/beauty-session.train.inter', index=False, sep='\t')

**Comment by chenyuwuxin** [comment]
@LimQueen 
如果您之前的header为`user_id item_id_list item_id`
那么第三行代码应该改为`df = df.rename(columns={'user_id':'user_id:token', 'item_id_list':'item_id_list:token_seq','item_id':'item_id:token'})` 才可以完成修改吧。

**Comment by LimQueen** [comment]
@chenyuwuxin 
噢不好意思，我完成修改的代码是您这个，抱歉我发错了。发给您那个代码是我用来确认表头改好写的代码。

**Comment by chenyuwuxin** [comment]
@LimQueen 请问train，val和test文件是否都已经修改？

**Comment by LimQueen** [comment]
@chenyuwuxin 
修改好了的。

**Comment by LimQueen** [comment]
@chenyuwuxin 
方便的，实在是不好意思耽误您这么长时间！！

**Comment by LimQueen** [comment]
@chenyuwuxin 
请问我应该怎样联系您呢？我的邮箱是liriusy@163.com。

**Comment by chenyuwuxin** [comment]
@LimQueen 看来还是数据集的格式错误，我修改好发你了，请查收。

**Comment by LimQueen** [comment]
@chenyuwuxin 
您好，请问一下：
我的测试集不是从训练集中划分出来的，是缺失item_id希望模型预测的。我在run_recbole.py文件中定义了输出文件：
parser.add_argument('--output_file', type=str, default='hyper_example.result', help='output file')

但貌似没能找到模型预测得到的输出文件。
麻烦再次请教您！！

**Comment by chenyuwuxin** [comment]
@LimQueen 您好，测试集必须是有item_id的，而不是待预测的数据。如果您想做预测，请参考run_example/case_study_example.py [Case Study](https://recbole.io/docs/user_guide/usage/case_study.html)。
