### ISSUE TITLE
使用疑问 如何在kg模型中使用AUC等指标?

### ISSUE THREAD

**Issue by Kongxiangzhouye** [RUCAIBox/RecBole#1332]
您好，如题目所示，我想把kg模型的评价指标换成AUC并遵照文档所示在yaml中修改了如下信息
其中rating我已经提前处理成只有0和1的形式
```yaml
LABEL_FIELD: rating
eval_args:
    mode: labeled
valid_metric: AUC
metrics: ['AUC', 'LogLoss']
topk: [10,20]
neg_sampling: None
```
其余未修改的配置都遵循overall.yaml中的配置，但是当我运行后却报出了如下错误
```
AUC EvaluatorType.VALUE
LogLoss EvaluatorType.VALUE
labeled EvaluatorType.VALUE
29 Jun 09:31    INFO  
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = dataset/book-crossing
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
neg_sampling = None
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'mode': 'labeled', 'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user'}
repeatable = False
metrics = ['AUC', 'LogLoss']
topk = [10, 20]
valid_metric = AUC
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
LABEL_FIELD = label
field_separator = 
seq_separator =  
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp'], 'kg': ['head_id', 'relation_id', 'tail_id'], 'link': ['item_id', 'entity_id']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = [0,inf)
item_inter_num_interval = [0,inf)
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = None
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
benchmark_filename = None

Other Hyper Parameters: 
wandb_project = recbole
require_pow = False
embedding_size = 64
n_iter = 1
aggregator = sum
reg_weight = 1e-07
neighbor_sample_size = 4
MODEL_TYPE = ModelType.KNOWLEDGE
MODEL_INPUT_TYPE = InputType.PAIRWISE
eval_type = EvaluatorType.VALUE
device = cuda
train_neg_sample_args = {'strategy': 'none'}
eval_neg_sample_args = {'strategy': 'none', 'distribution': 'none'}


29 Jun 09:31    INFO  book-crossing
The number of users: 17861
Average actions of users: 7.824524076147816
The number of items: 14968
Average actions of items: 9.336941270795752
The number of inters: 139746
The sparsity of the dataset: 99.94772791289802%
Remain Fields: ['entity_id', 'user_id', 'item_id', 'rating', 'timestamp', 'head_id', 'relation_id', 'tail_id']
The number of entities: 77904
The number of relations: 27
The number of triples: 151500
The number of items that have been linked to KG: 14967
Traceback (most recent call last):
  File "run_recbole.py", line 31, in <module>
    run_recbole(model=args.model, dataset=args.dataset)
  File "/output/RecBole/recbole/quick_start/quick_start.py", line 45, in run_recbole
    train_data, valid_data, test_data = data_preparation(config, dataset)
  File "/output/RecBole/recbole/data/utils.py", line 148, in data_preparation
    kg_sampler = KGSampler(dataset, config['train_neg_sample_args']['distribution'])
KeyError: 'distribution'
```
我不知道这个错误是哪里配置的问题，应该怎么去修改，希望您能帮帮我，谢谢。

**Comment by chenyuwuxin** [comment]
@Kongxiangzhouye 您好，KG类型的模型一般采样负采样设置负例，数据集出现过的交互作为正例。因此，你只需要将数据集的负例(label 为 0 )的交互移除，然后enable 负采样模式，示例配置文件如下：

```
LABEL_FIELD: rating
eval_args:
    mode: labeled
valid_metric: AUC
metrics: ['AUC', 'LogLoss']
topk: [10,20]
```

**Comment by Kongxiangzhouye** [comment]
> 



> @Kongxiangzhouye您好，您好，一般将负载类型的负载示例，数据显示类型的负载示例，作为随后的辅助设置，您只需将 KG 类型的数据用于负载示例，因此可以将其用于负载类型的负载示例。模式，示例配置文件如下：
> 
> ```
> LABEL_FIELD: rating
> eval_args:
>     mode: labeled
> valid_metric: AUC
> metrics: ['AUC', 'LogLoss']
> topk: [10,20]
> ```

换成这个后，在train完第一轮后的Evaluate报如下错误
```
Traceback (most recent call last):
  File "run_recbole.py", line 31, in <module>
    run_recbole(model=args.model, dataset=args.dataset)
  File "/output/RecBole/recbole/quick_start/quick_start.py", line 57, in run_recbole
    train_data, valid_data, saved=saved, show_progress=config['show_progress']
  File "/output/RecBole/recbole/trainer/trainer.py", line 352, in fit
    valid_score, valid_result = self._valid_epoch(valid_data, show_progress=show_progress)
  File "/output/RecBole/recbole/trainer/trainer.py", line 209, in _valid_epoch
    valid_result = self.evaluate(valid_data, load_best_model=False, show_progress=show_progress)
  File "/usr/local/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/output/RecBole/recbole/trainer/trainer.py", line 478, in evaluate
    self.eval_collector.eval_batch_collect(scores, interaction, positive_u, positive_i)
  File "/output/RecBole/recbole/evaluator/collector.py", line 178, in eval_batch_collect
    self.data_struct.update_tensor('data.label', interaction[self.label_field].to(self.device))
  File "/output/RecBole/recbole/data/interaction.py", line 131, in __getitem__
    return self.interaction[index]
KeyError: 'label'
```

**Comment by chenyuwuxin** [comment]
@Kongxiangzhouye 您好，看起来是`LABEL_FIELD: rating` 没有起作用。请不要修改overall.yaml文件，因为其中部分字段由于优先级较低可能被替换，而应通过新建一个运行配置文件，例如test.yaml，内容为：
```
LABEL_FIELD: rating
eval_args:
    mode: labeled
valid_metric: AUC
metrics: ['AUC', 'LogLoss']
topk: [10,20]

```
通过命令行指定文件：python run_recbole.py --config_files=test.yaml --model=KGAT --dataset=book-crossing运行。

**Comment by Kongxiangzhouye** [comment]
> @Kongxiangzhouye 您好，看起来是`LABEL_FIELD: rating` 没有起作用。请不要修改overall.yaml文件，因为其中部分字段由于优先级较低可能被替换，而应通过新建一个运行配置文件，例如test.yaml，内容为：
> 
> ```
> LABEL_FIELD: rating
> eval_args:
>     mode: labeled
> valid_metric: AUC
> metrics: ['AUC', 'LogLoss']
> topk: [10,20]
> ```
> 
> 通过命令行指定文件：python run_recbole.py --config_files=test.yaml --model=KGAT --dataset=book-crossing运行。

您好，按照这个做法确实可以了，但是根据api文档里配置方法的优先级是：命令行>参数字典>配置文件>默认设置
我修改的部分实际上是在recbole/properties/model/KGCN.yaml 并且命令行、参数字典、配置文件都没有配置，按理说不应该会发生替换呀，还是说在默认设置里还有一个优先级关系。

**Comment by chenyuwuxin** [comment]
@Kongxiangzhouye 没错，我们有很多默认的内置配置文件，它们存在不同的优先级顺序。

**Comment by Kongxiangzhouye** [comment]
哈哈，好的好的，那我以后就改命令行和配置文件好了，谢谢啦~
