### ISSUE TITLE
[🐛BUG] BERT4Rec "index out of range in self" for custom dataset

### ISSUE THREAD

**Issue by ajster1** [RUCAIBox/RecBole#1347]
I'm working with BERT4Rec and have successfully processed data in the below format:

```
session_id:token	item_id:token	timestamp:float
0	23301	1654178766
1	30936	1652712846
2	20856	1652831141
3	20716	1653507732
4	16646	1650123860
```

When I try to process the same data in this format:

```
session_id:token	item_id_list:token_seq	item_id:token	item_length:token
5679	5680	8118	1
5679	5680 8118	5650	2
5679	5680 8118 5650	1345	3
551063	16451	30443	1
551063	16451 30443	31491	2
```

I get the below error:

```
Traceback (most recent call last):
  File "C:\projects\sbr\lmtrain_cs.py", line 97, in <module>
    best_valid_score, best_valid_result = trainer.fit(
  File "C:\Users\AJ\AppData\Local\Programs\Python\Python39\lib\site-packages\recbole\trainer\trainer.py", line 337, in fit
    train_loss = self._train_epoch(train_data, epoch_idx, show_progress=show_progress)
  File "C:\Users\AJ\AppData\Local\Programs\Python\Python39\lib\site-packages\recbole\trainer\trainer.py", line 182, in _train_epoch
    losses = loss_func(interaction)
  File "C:\Users\AJ\AppData\Local\Programs\Python\Python39\lib\site-packages\recbole\model\sequential_recommender\bert4rec.py", line 198, in calculate_loss
    seq_output = self.forward(masked_item_seq)
  File "C:\Users\AJ\AppData\Local\Programs\Python\Python39\lib\site-packages\recbole\model\sequential_recommender\bert4rec.py", line 162, in forward
    position_embedding = self.position_embedding(position_ids)
  File "C:\Users\AJ\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\AJ\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\sparse.py", line 158, in forward
    return F.embedding(
  File "C:\Users\AJ\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\functional.py", line 2199, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
IndexError: index out of range in self
```

If I change 'MAX_ITEM_LIST_LENGTH' from 50 to 242, which is the max item_length in the data set, I am able to get it to work but run into memory issues possibly because of the larger item list length. I don't have this problem with other algorithms like GRU4Rec, NARM, STAMP, etc.

Is BERT4Rec handling the data differently compared to the others?

**Comment by ajster1** [comment]
It's what I expected but was hoping for a way to automatically truncate.  I updated my pre-processing script to truncate at max item list length and it fixed the index error. Thanks for clarifying.
