### ISSUE TITLE
[🐛BUG] 使用benchmark_filename时报错AttributeError: 'SequentialDataset' object has no attribute 'item_id_list_field'

### ISSUE THREAD

**Issue by hyl2000** [RUCAIBox/RecBole#1442]
您好，我已经详细阅读了相关的issue，并且对数据集做了相关处理，但是运行时仍会报AttributeError: 'SequentialDataset' object has no attribute 'item_id_list_field'的错误，我的设置如下
USER_ID_FIELD: 'user_id'
ITEM_ID_FIELD: 'item_id'
RATING_FIELD: 'rating'
ITEM_ID_LIST_FIELD: 'item_id_list_field'
# TIME_FIELD: timestamp
seq_len: ~

# Label for Point-wise DataLoader
LABEL_FIELD: label
threshold: ~

# NegSample Prefix for Pair-wise DataLoader
NEG_PREFIX: neg_

# Selectively Loading
load_col:
    inter: ['user_id', 'item_id', 'rating', 'item_id_list', 'item_id_list_field']
并且数据集中的定义也为
user_id:token	item_id:token	rate:float	item_id_list_field:token_seq
假设user1交互序列为6 5 4 3，当与3交互时为
1	3	1	6 5 4
请问还需要进行特别设置么，谢谢！

**Comment by hyl2000** [comment]
不好意思，格式出现错误，设置为
USER_ID_FIELD: 'user_id'
ITEM_ID_FIELD: 'item_id'
RATING_FIELD: 'rating'
ITEM_ID_LIST_FIELD: 'item_id_list_field'
load_col:
    inter: ['user_id', 'item_id', 'rating', 'item_id_list', 'item_id_list_field']

**Comment by hyl2000** [comment]
我在更改数据集中item_id_list_filed为item_id_list后不再出现上述错误
现在设置改为
field_separator: "\t"
seq_separator: " "
USER_ID_FIELD: 'user_id'
ITEM_ID_FIELD: 'item_id'
RATING_FIELD: 'rating'
seq_len: ~
LABEL_FIELD: label
threshold: ~
NEG_PREFIX: neg_
load_col:
    inter: ['user_id', 'item_id', 'rating', 'item_id_list']
但是出现了新的错误
Traceback (most recent call last):
  File "run_recbole.py", line 25, in <module>
    run_recbole(model=args.model, dataset=args.dataset, config_file_list=config_file_list)
  File "E:\实验室资料\RecBole-master\RecBole-master\recbole\quick_start\quick_start.py", line 56, in run_recbole
    best_valid_score, best_valid_result = trainer.fit(
  File "E:\实验室资料\RecBole-master\RecBole-master\recbole\trainer\trainer.py", line 335, in fit
    train_loss = self._train_epoch(train_data, epoch_idx, show_progress=show_progress)
  File "E:\实验室资料\RecBole-master\RecBole-master\recbole\trainer\trainer.py", line 181, in _train_epoch
    losses = loss_func(interaction)
  File "E:\实验室资料\RecBole-master\RecBole-master\recbole\model\sequential_recommender\sasrec.py", line 111, in calculate_loss
    seq_output = self.forward(item_seq, item_seq_len)
  File "E:\实验室资料\RecBole-master\RecBole-master\recbole\model\sequential_recommender\sasrec.py", line 99, in forward
    input_emb = self.dropout(input_emb)
  File "C:\Users\RonHuang\.conda\envs\py38\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\RonHuang\.conda\envs\py38\lib\site-packages\torch\nn\modules\dropout.py", line 58, in forward
    return F.dropout(input, self.p, self.training, self.inplace)
  File "C:\Users\RonHuang\.conda\envs\py38\lib\site-packages\torch\nn\functional.py", line 1252, in dropout
    return _VF.dropout_(input, p, training) if inplace else _VF.dropout(input, p, training)
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
请问有调试方案么，谢谢！

**Comment by hyl2000** [comment]
经过排查，问题貌似是item_id_list长度不能为0，所以模型是不支持冷启动么，谢谢！

**Comment by zhengbw0324** [comment]
@hyl2000 
您好，我们的配置文件里并没有`ITEM_ID_LIST_FIELD`这一项，item list 是在数据集加载过程中根据用户交互记录生成，您出现问题的原因应该是没有设置`TIME_FIELD`，因为在生成用户交互序列过程中需要根据 timestamp 排序。
