### ISSUE TITLE
[🐛BUG] eval_args.mode 为 label时，报错 TypeError

### ISSUE THREAD

**Issue by leoleoasd** [RUCAIBox/RecBole#1473]
**描述这个 bug**

运行 BPR 模型时，如果评测指标是`recall`，则会有以下的错误提示
```
Traceback (most recent call last):
  File "/home/yuxlu/RecBole-PJF/run_recbole_pjf.py", line 20, in <module>
    run_recbole_pjf(model=args.model, dataset=args.dataset, config_file_list=config_file_list)
  File "/home/yuxlu/RecBole-PJF/recbole_pjf/quick_start/quick_start.py", line 46, in run_recbole_pjf
    best_valid_score, best_valid_result = trainer.fit(
  File "/home/yuxlu/anaconda3/envs/aibox/lib/python3.9/site-packages/recbole/trainer/trainer.py", line 352, in fit
    valid_score, valid_result = self._valid_epoch(valid_data, show_progress=show_progress)
  File "/home/yuxlu/anaconda3/envs/aibox/lib/python3.9/site-packages/recbole/trainer/trainer.py", line 209, in _valid_epoch
    valid_result = self.evaluate(valid_data, load_best_model=False, show_progress=show_progress)
  File "/home/yuxlu/anaconda3/envs/aibox/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/yuxlu/anaconda3/envs/aibox/lib/python3.9/site-packages/recbole/trainer/trainer.py", line 475, in evaluate
    interaction, scores, positive_u, positive_i = eval_func(batched_data)
  File "/home/yuxlu/anaconda3/envs/aibox/lib/python3.9/site-packages/recbole/trainer/trainer.py", line 424, in _neg_sample_batch_eval
    batch_user_num = positive_u[-1] + 1
TypeError: 'NoneType' object is not subscriptable
```
如果指标选择auc，则算出来的auc都是nan

**如何复现**
overall.yaml:
```
# general
gpu_id: 0
use_gpu: True
seed: 2020
state: DEBUG
reproducibility: True
data_path: 'dataset/'
checkpoint_dir: 'saved'
show_progress: True
save_dataset: False
dataset_save_path: ~
save_dataloaders: False
dataloaders_save_path: ~
log_wandb: True
wandb_project: 'recbole'

# training settings
epochs: 300
train_batch_size: 300
learner: adam
learning_rate: 0.001
neg_sampling:
  uniform: 1
eval_step: 1
stopping_step: 10
clip_grad_norm: ~
# clip_grad_norm:  {'max_norm': 5, 'norm_type': 2}
weight_decay: 0.0
loss_decimal_place: 4
require_pow: False

train_neg_sample_args: {}

# evaluation settings
eval_args:
  # split: {'RS':[0.8,0.1,0.1]}
  split: {'LS': 'valid_and_test'}
  group_by: none
  order: RO
  mode: labeled
repeatable: False
metrics: ["Recall"]
topk: [5]
valid_metric: Recall@5
valid_metric_bigger: True
eval_batch_size: 1024
metric_decimal_place: 4
```

dataset.yaml:
```
# Atomic File Format
field_separator: "\t"
seq_separator: " "

# Common Features
USER_ID_FIELD: member_id
ITEM_ID_FIELD: job_id
#RATING_FIELD: rating
#TIME_FIELD: timestamp
#DIRECT_FIELD: direct
seq_len: ~
# Label for Point-wise DataLoader
LABEL_FIELD: label
threshold:
   label: 0.5
# NegSample Prefix for Pair-wise DataLoader
NEG_PREFIX: neg_
# neg_sampling: null
# Text Model Needed
USER_DOC_FIELD: summary
ITEM_DOC_FIELD: description

# Selectively Loading
load_col:
    inter: [member_id, job_id, label]
    udoc: [member_id, summary]
    idoc: [job_id, description]
    user: [member_id]
    item: [job_id]
unload_col: ~
unused_col: ~

# Filtering
rm_dup_inter: ~
val_interval: ~
filter_inter_by_user_or_item: True
user_inter_num_interval: ~
item_inter_num_interval: ~

# Preprocessing
alias_of_user_id: ~
alias_of_item_id: ~
alias_of_entity_id: ~
alias_of_relation_id: ~
preload_weight: ~
normalize_field: ~

biliteral: False
```

**实验环境（请补全下列信息）：**
- 操作系统: linux
- RecBole 版本 1.0.1
- Python 版本 3.9
- PyTorch 版本 1.13
- cudatoolkit 版本 11.3

**Comment by AoiDragon** [comment]
@leoleoasd 非常抱歉没有及时回复，RecBole-PJF是RecBole 2.0的子库，您可以在[对应仓库](https://github.com/RUCAIBox/RecBole-PJF/issues)下提问。
