### ISSUE TITLE
[🐛BUG] 运行SHAN时报错

### ISSUE THREAD

**Issue by ShelveyJ** [RUCAIBox/RecBole#1486]
使用如下代码运行SHAN时
`from recbole.quick_start import run_recbole

parameter_dict = {
   'train_neg_sample_args': None,
}
run_recbole(model='SHAN', dataset='ml-100k', config_dict=parameter_dict)`
得到以下错误
`Trainable parameters: 176448
Traceback (most recent call last):
  File "D:\academic\code\RecBole-master\test.py", line 6, in <module>
    run_recbole(model='SHAN', dataset='ml-100k', config_dict=parameter_dict)
  File "D:\academic\code\RecBole-master\recbole\quick_start\quick_start.py", line 81, in run_recbole
    flops = get_flops(model, dataset, config["device"], logger, transform)
  File "D:\academic\code\RecBole-master\recbole\utils\utils.py", line 267, in get_flops
    model = copy.deepcopy(model)
  File "E:\anaconda3\envs\recbole\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "E:\anaconda3\envs\recbole\lib\copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "E:\anaconda3\envs\recbole\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "E:\anaconda3\envs\recbole\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "E:\anaconda3\envs\recbole\lib\copy.py", line 153, in deepcopy
    y = copier(memo)
  File "E:\anaconda3\envs\recbole\lib\site-packages\torch\_tensor.py", line 85, in __deepcopy__
    raise RuntimeError("Only Tensors created explicitly by the user "
RuntimeError: Only Tensors created explicitly by the user (graph leaves) support the deepcopy protocol at the moment`

**Comment by zhengbw0324** [comment]
@ShelveyJ 您好！
感谢您的提醒，我们已在[#1488](https://github.com/RUCAIBox/RecBole/pull/1488)修复了这个Bug，您可以在 GitHub 下载最新的代码进行使用。
