### ISSUE TITLE
[💡SUG/BUG] MultiVAE without mlp_hidden_size

### ISSUE THREAD

**Issue by mmosc** [RUCAIBox/RecBole#1519]
Hi and thank you for this great library :) 

**Problem encountered**
I was trying to run a hyperparameter search on MultiVAE. I would like to follow the hyperparameters of [this paper](https://karapostk.github.io/assets/pdf/melchiorre2021investigating.pdf):
> For MultiVAE, we explore different (symmetric) architectures and annealing procedures. [...]We examine various architectures, namely I-500-I, I-1000-I, and I-1000-500-1000-I. In the
architectures, I is the total number of tracks, the numbers in the middle denote the dimensions of the latent embeddings, and
the numbers in between (when existing) are the intermediary dimensions of the feed-forward networks with hyperbolic tangent
non-linearity.

As you can see, I would like to have either a single layer (from `num_items` to `latent_dimension`).

Since [the code of MultiVAE]() does the following
```

        self.encode_layer_dims = [self.n_items] + self.layers + [self.lat_dim]
        self.decode_layer_dims = [int(self.lat_dim / 2)] + self.encode_layer_dims[::-1][
            1:
        ]

        self.encoder = self.mlp_layers(self.encode_layer_dims)
        self.decoder = self.mlp_layers(self.decode_layer_dims)
```
I tried including an empty list among the choices for `mlp_hidden_size`, like this:
```
latent_dimension choice [500, 1000]
mlp_hidden_size choice [[], [1000]]
``` 

However, this gives back the error:
```
Traceback (most recent call last):
  File "run_hyper.py", line 127, in <module>
    hyperopt_tune(args)
  File "run_hyper.py", line 30, in hyperopt_tune
    hp = HyperTuning(
  File "/home/marta/jku/FairInterplay/recbole/trainer/hyper_tuning.py", line 205, in __init__
    self.max_evals = _spacesize(self.space)
  File "/home/marta/jku/FairInterplay/recbole/trainer/hyper_tuning.py", line 66, in _spacesize
    params = _parameters(space)
  File "/home/marta/jku/FairInterplay/recbole/trainer/hyper_tuning.py", line 59, in _parameters
    values = [literal.obj for literal in node.pos_args[1:]]
  File "/home/marta/jku/FairInterplay/recbole/trainer/hyper_tuning.py", line 59, in <listcomp>
    values = [literal.obj for literal in node.pos_args[1:]]
AttributeError: 'Apply' object has no attribute 'obj'
```

**My questions**
1. Is it in general possible to have a MultiVAE without a mlp layer? If so, how can I set it up?
2. Is it possible to include both mlp and no mlp layer in the params file, to run a single hyperparameter search?

Cheers, 
Marta

**Comment by mmosc** [comment]
I found the solution:

`mlp_hidden_size choice ['[]', '[1000]']`

Cheers!
