### ISSUE TITLE
DSSM模型報錯

### ISSUE THREAD

**Issue by emilyjeng** [RUCAIBox/RecBole#1583]
您好，我在使用yelp2022在DSSM模型時，會產生以下錯誤:
Traceback (most recent call last):
  File "run_recbole.py", line 48, in <module>
    run_recbole(
  File "/Emily/RecBole-master/recbole/quick_start/quick_start.py", line 81, in run_recbole
    flops = get_flops(model, dataset, config["device"], logger, transform)
  File "/Emily/RecBole-master/recbole/utils/utils.py", line 345, in get_flops
    wrapper(*inputs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1111, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Emily/RecBole-master/recbole/utils/utils.py", line 286, in forward
    return self.model.predict(interaction)
  File "/Emily/RecBole-master/recbole/model/context_aware_recommender/dssm.py", line 111, in predict
    return self.sigmoid(self.forward(interaction))
  File "/Emily/RecBole-master/recbole/model/context_aware_recommender/dssm.py", line 100, in forward
    user_dnn_out = self.user_mlp_layers(embed_user.view(batch_size, -1))
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1111, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Emily/RecBole-master/recbole/model/layers.py", line 89, in forward
    return self.mlp_layers(input_feature)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1129, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1129, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x20 and 30x256)

**Comment by chenyuwuxin** [comment]
@emilyjeng 您好，感谢您的关注！
由于我们提供的yelp数据集一般是没有.user和.item文件的，请问您是否方便提供一小部分您使用的数据集以便我们测试呢？

**Comment by emilyjeng** [comment]
@chenyuwuxin 您好，我從您們提供的google雲端中下載yelp2022檔案，且裡面有.user和.item文件
<img width="609" alt="image" src="https://user-images.githubusercontent.com/74802442/208250959-d45cdb17-57a7-47c2-8b0f-be681d7728ef.png">

**Comment by emilyjeng** [comment]
@chenyuwuxin 您好!我要重新下載數據集嗎?因為我pip install --upgrade recbole後，狀況還是一樣
