### ISSUE TITLE
General 與Sequential是否能用'AUC', 'LogLoss', 'MAE', 'RMSE'評估指標

### ISSUE THREAD

**Issue by emilyjeng** [RUCAIBox/RecBole#1589]
您好！！以下是我的問題，我使用RecVAE：

我的評估指標設定如下：
eval_args:
  split: {'RS':[0.8, 0.1, 0.1]}
  group_by: ~
  mode: labeled
  order: RO
valid_metric: AUC
metrics: ['AUC', 'LogLoss']

會出現以下錯誤:
19 Dec 07:34    INFO  Finished training, best eval result in epoch -1
Traceback (most recent call last):
  File "run_recbole.py", line 48, in <module>
    run_recbole(
  File "/Emily/RecBole-master/recbole/quick_start/quick_start.py", line 94, in run_recbole
    test_result = trainer.evaluate(
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/Emily/RecBole-master/recbole/trainer/trainer.py", line 583, in evaluate
    checkpoint = torch.load(checkpoint_file, map_location=self.device)
  File "/opt/conda/lib/python3.8/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/opt/conda/lib/python3.8/site-packages/torch/serialization.py", line 231, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/opt/conda/lib/python3.8/site-packages/torch/serialization.py", line 212, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'saved/RecVAE-Dec-19-2022_07-33-59.pth'
<img width="508" alt="image" src="https://user-images.githubusercontent.com/74802442/208382698-aa9afc2a-2877-4f47-a293-dc6d7c15b7a9.png">

而且我發現auc都為nan，且執行階段會出現WARNING  No negative samples in y_true, false positive value should be meaningless
而當跑rank base 就可以正常儲存執行，請問有甚麼方法可以解決?

**Comment by Sherry-XLL** [comment]
@emilyjeng 您好，RecVAE 是基于变分自编码器实现的推荐模型，是针对于基于排序的模型进行设计的，不建议使用 'AUC', 'LogLoss', 'MAE', 'RMSE' 等评估指标。

**Comment by emilyjeng** [comment]
@Sherry-XLL 您好，但我查看#1584、#1008和#1073提到的，評估指標是可以改成的AUC
