### ISSUE TITLE
嘗試建立yelp知識圖譜

### ISSUE THREAD

**Issue by emilyjeng** [RUCAIBox/RecBole#1597]
您好!我嘗試簡單建立了yelp的知識圖譜，在.kg檔案中，我將head_id:token設為iten_id:token，relation_id:token設為location.shop.location，tail_id:token設為categories:token_seq
如下所示:
<img width="928" alt="image" src="https://user-images.githubusercontent.com/74802442/208854309-8d75e2a2-f49d-4d76-8a2d-e54a80f3c150.png">
在.link檔案中，item_id:token保持不變，entity_id:token設為categories:token_seq，如下所示:
<img width="789" alt="image" src="https://user-images.githubusercontent.com/74802442/208854619-eb9a18c3-0476-4547-9aa7-39d99e450acf.png">

但在我執行時會遇到錯誤，如下所示:

Traceback (most recent call last):
  File "run_recbole.py", line 48, in <module>
    run_recbole(
  File "/Emily/RecBole-master/recbole/quick_start/quick_start.py", line 69, in run_recbole
    dataset = create_dataset(config)
  File "/Emily/RecBole-master/recbole/data/utils.py", line 70, in create_dataset
    dataset = dataset_class(config)
  File "/Emily/RecBole-master/recbole/data/dataset/kg_dataset.py", line 68, in __init__
    super().__init__(config)
  File "/Emily/RecBole-master/recbole/data/dataset/dataset.py", line 108, in __init__
    self._from_scratch()
  File "/Emily/RecBole-master/recbole/data/dataset/dataset.py", line 120, in _from_scratch
    self._data_processing()
  File "/Emily/RecBole-master/recbole/data/dataset/dataset.py", line 168, in _data_processing
    self._normalize()
  File "/Emily/RecBole-master/recbole/data/dataset/dataset.py", line 710, in _normalize
    feat[field] = norm(feat[field].values)
  File "/Emily/RecBole-master/recbole/data/dataset/dataset.py", line 698, in norm
    mx, mn = max(arr), min(arr)
ValueError: max() arg is an empty sequence

我不理解該如何處理這問題?

**Comment by chenyuwuxin** [comment]
@emilyjeng 您好，请问是否可以提供一下您运行的配置文件？

**Comment by emilyjeng** [comment]
檔案連結如下:
https://drive.google.com/drive/folders/10-2Q8zW3FC_hylvKXorfohL8w0sw1Dm-?usp=sharing

**Comment by chenyuwuxin** [comment]
@emilyjeng 您好，請嘗試將normalize_all設置爲False

**Comment by emilyjeng** [comment]
@chenyuwuxin 感謝解答!我將normalize_all設置爲False後，出現報錯如下：

ValueError: Some users have interacted with all items, which we can not sample negative items for them. Please set `user_inter_num_interval` to filter those users.

但如上面我的設置檔，我有將user_inter_num_interval設置為user_inter_num_interval: "[10,inf)"，請問該如何設置?

**Comment by chenyuwuxin** [comment]
@emilyjeng 您好，這個問題是由於數據集中存在某個用戶或者物品的交互過少，導致它交互的對象全被過濾掉了。您可以嘗試降低**user_inter_num_interval**和**item_inter_num_interval**來解決這個問題。

**Comment by emilyjeng** [comment]
@chenyuwuxin 您好!我後來發現是entity_kg_num_interval和relation_kg_num_interval的數量問題，當我降低後，產生了另一個錯誤
Traceback (most recent call last):
  File "run_recbole.py", line 48, in <module>
    run_recbole(
  File "/Emily/RecBole-master/recbole/quick_start/quick_start.py", line 69, in run_recbole
    dataset = create_dataset(config)
  File "/Emily/RecBole-master/recbole/data/utils.py", line 70, in create_dataset
    dataset = dataset_class(config)
  File "/workspace-nfs/JMD220-dev/NLP/Emily/RecBole-master/recbole/data/dataset/kg_dataset.py", line 68, in __init__
    super().__init__(config)
  File "/Emily/RecBole-master/recbole/data/dataset/dataset.py", line 108, in __init__
    self._from_scratch()
  File "/Emily/RecBole-master/recbole/data/dataset/dataset.py", line 120, in _from_scratch
    self._data_processing()
  File "/Emily/RecBole-master/recbole/data/dataset/dataset.py", line 164, in _data_processing
    self._remap_ID_all()
  File "/Emily/RecBole-master/recbole/data/dataset/kg_dataset.py", line 407, in _remap_ID_all
    self._merge_item_and_entity()
  File "/Emily/RecBole-master/recbole/data/dataset/kg_dataset.py", line 349, in _merge_item_and_entity
    entity_id_map[i] = new_item_token2id[self.entity2item[entity_token[i]]]
KeyError: 'LR36pCDNMp08zRLvjGYVjw'
