### ISSUE TITLE
如何对自定义的模型进行参数调优

### ISSUE THREAD

**Issue by lalunex** [RUCAIBox/RecBole#1600]
您好，我遇到的错误栈如下，那么如何解决下面的问题呢？

    running parameters:
    {'embedding_size': 100, 'learning_rate': 0.01506116863474379, 'train_batch_size': 256}
      0%|                                   | 0/100 [00:00<?, ?trial/s, best loss=?]job exception: `model_name` [HSD] is not the name of an existing model.
    
      0%|                                   | 0/100 [00:00<?, ?trial/s, best loss=?]
    Traceback (most recent call last):
      File "/home/bigdata6/ll/hsd_sup_cl/parameter_tuning.py", line 26, in <module>
        hp.run()
      File "/home/bigdata6/anaconda3/envs/ll_torch10/lib/python3.9/site-packages/recbole/trainer/hyper_tuning.py", line 411, in run
        fmin(
      File "/home/bigdata6/anaconda3/envs/ll_torch10/lib/python3.9/site-packages/hyperopt/fmin.py", line 586, in fmin
        rval.exhaust()
      File "/home/bigdata6/anaconda3/envs/ll_torch10/lib/python3.9/site-packages/hyperopt/fmin.py", line 364, in exhaust
        self.run(self.max_evals - n_done, block_until_done=self.asynchronous)
      File "/home/bigdata6/anaconda3/envs/ll_torch10/lib/python3.9/site-packages/hyperopt/fmin.py", line 300, in run
        self.serial_evaluate()
      File "/home/bigdata6/anaconda3/envs/ll_torch10/lib/python3.9/site-packages/hyperopt/fmin.py", line 178, in serial_evaluate
        result = self.domain.evaluate(spec, ctrl)
      File "/home/bigdata6/anaconda3/envs/ll_torch10/lib/python3.9/site-packages/hyperopt/base.py", line 892, in evaluate
        rval = self.fn(pyll_rval)
      File "/home/bigdata6/anaconda3/envs/ll_torch10/lib/python3.9/site-packages/recbole/trainer/hyper_tuning.py", line 346, in trial
        result_dict = self.objective_function(config_dict, self.fixed_config_file_list)
      File "/home/bigdata6/anaconda3/envs/ll_torch10/lib/python3.9/site-packages/recbole/quick_start/quick_start.py", line 133, in objective_function
        config = Config(config_dict=config_dict, config_file_list=config_file_list)
      File "/home/bigdata6/anaconda3/envs/ll_torch10/lib/python3.9/site-packages/recbole/config/configurator.py", line 86, in __init__
        self.model, self.model_class, self.dataset = self._get_model_and_dataset(
      File "/home/bigdata6/anaconda3/envs/ll_torch10/lib/python3.9/site-packages/recbole/config/configurator.py", line 214, in _get_model_and_dataset
        final_model_class = get_model(final_model)
      File "/home/bigdata6/anaconda3/envs/ll_torch10/lib/python3.9/site-packages/recbole/utils/utils.py", line 79, in get_model
        raise ValueError(
    ValueError: `model_name` [HSD] is not the name of an existing model.

下面是我进行参数调优的文件，下面的main函数是按照run_recbole来定义的

    from recbole.trainer import HyperTuning
    from recbole.quick_start import objective_function
    from run_hsd import main
    from utils.parser import parse_args

    hp = HyperTuning(objective_function=objective_function,
                     algo='random', early_stop=10,
                     max_evals=100, params_file='para_tune/tuning.hyper',
                     fixed_config_file_list=['./para_tune/tune_fixed_para.yml'])
    
    
    def objective_function(config_dict=None, config_file_list=None):
        args = parse_args()
        dic = vars(args)
    
        result = main(
            model=dic['model_name'], dataset=dic['dataset'],
            config_file_list=config_file_list, config_dict=config_dict, saved=True
        )
    
        return result
    
    
    if __name__ == '__main__':
        # run
        hp.run()
        # export result to the file
        hp.export_result(output_file=r'./para_tune/hyper_example.result')
        # print best parameters
        print('best params: ', hp.best_params)
        # print best result
        print('best result: ')
        print(hp.params2result[hp.params2str(hp.best_params)])

固定参数文件tune_fixed_para.yml：

    model: 'HSD'

调优参数文件tuning.hyper：

    learning_rate loguniform -8,0
    embedding_size choice [64,100,128,256]
    train_batch_size choice [256, 512, 1024]

**Comment by lalunex** [comment]
你好，如何解决这个问题呢？

**Comment by Sherry-XLL** [comment]
@lalunex 您好，产生问题的原因主要是您将 RecBole 作为内置的包去调用，因此您定义的新模型并不在 `recbole/model` 中。为了更方便地对自定义模型进行参数调优，建议您按照[文档](https://recbole.io/docs/developer_guide/customize_models.html)提供的方式在源代码中加入新模型，再进行超参数的调节。

感谢您对伯乐的关注，希望我的回答能解决您的问题。

**Comment by lalunex** [comment]
您好，我已经按照文档实现了predict()，__init__()函数，但是由于模型的需求，我对calcualte_loss()函数进行了重构（参数个数增加了，我将函数名重构为reweight_calcualte_loss()）；同时，我也没有指定input_type 

我的问题是：
1、方法接口内容（参数个数，函数名）一定要和文档一样吗？
2、是否只需要把模型文件移动到rebole/model里面，并且把其对应的trainer也移动到相应的位置，这样就可以使用自定义的trainer来对自定义的model进行调参吗？
3、如果是这样的话，是应该把trainer移动到recbole/trainer里面吗？

**Comment by Sherry-XLL** [comment]
您好，@lalunex！如果您对 calcualte_loss()函数进行了重构，trainer 也要进行相应地改变。

1. 接口的内容可以进行自定义的设置
2. 是的
3. 是的

**Comment by lalunex** [comment]
您好，@Sherry-XLL！，非常感谢，您的回答为我解开了很多疑问。

不过我很好奇，调参的过程是如何进行的？需要调节的参数如下：
```
learning_rate loguniform -8,0
embedding_size choice [64,100,128,256]
train_batch_size choice [256, 512, 1024]
```
每次都按照条件选取对应的值（learning_rate，embedding_size，train_batch_size），再将选取的值进行训练。那么最终需要进行多少次的训练呢？假如说有300k个参数，那么需要多少训练时间呢？
