### ISSUE TITLE
[🐛BUG] Cannot run "Quick-start From Source" smoothly due to numpy version

### ISSUE THREAD

**Issue by GinYoshida** [RUCAIBox/RecBole#1617]
**Describe the bug**
 After pip installation, the following AttributeError occured.

```
Traceback (most recent call last):
  File "C:\git\recbole\RecBole\run_recbole.py", line 48, in <module>
    run_recbole(
  File "C:\git\recbole\RecBole\recbole\quick_start\quick_start.py", line 88, in run_recbole
    best_valid_score, best_valid_result = trainer.fit(
  File "C:\git\recbole\RecBole\recbole\trainer\trainer.py", line 462, in fit
    valid_score, valid_result = self._valid_epoch(
  File "C:\git\recbole\RecBole\recbole\trainer\trainer.py", line 281, in _valid_epoch
    valid_result = self.evaluate(
  File "C:\git\recbole\.venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\git\recbole\RecBole\recbole\trainer\trainer.py", line 623, in evaluate
    result = self.evaluator.evaluate(struct)
  File "C:\git\recbole\RecBole\recbole\evaluator\evaluator.py", line 39, in evaluate
    metric_val = self.metric_class[metric].calculate_metric(dataobject)
  File "C:\git\recbole\RecBole\recbole\evaluator\metrics.py", line 84, in calculate_metric
    result = self.metric_info(pos_index)
  File "C:\git\recbole\RecBole\recbole\evaluator\metrics.py", line 90, in metric_info
    result = np.zeros_like(pos_index, dtype=np.float)
  File "C:\git\recbole\.venv\lib\site-packages\numpy\__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'float'. Did you mean: 'cfloat'?

```

**To Reproduce**
1. Just Install from source "https://recbole.io/install.html"
2. run the following commands in the quick start.

```
from recbole.quick_start import run_recbole
run_recbole()
```

 My numpy version is "numpy==1.24.1".

In according to this post, the numpy is not supporting from 1.24.
https://stackoverflow.com/questions/74844262/how-to-solve-error-numpy-has-no-attribute-float-in-python

**Desktop (please complete the following information):**
 - OS: Windows 11 Home 21H2
- RecBole Version 1.1.1
 - Python Version 3.10.7
- PyTorch Version 1.13.1
- cudatoolkit Version 11.8

**Countermeasure**
Just downgrading with `pip install numpy<1.24.0`
With numpy==1.23.5, it is working without issue.

Thank you for your great work!!

**Comment by chenyuwuxin** [comment]
@mrcabbage972 Hello, thanks for your attention to RecBole！
We have already fix this issue at [#1621](https://github.com/RUCAIBox/RecBole/pull/1621). Thanks for your feedback.
