### ISSUE TITLE
[🐛BUG] MCCLK使用ml-1m数据集报内存溢出错误

### ISSUE THREAD

**Issue by 1728435673** [RUCAIBox/RecBole#1634]
过滤数据集之后（修改了entity_kg_num_interval，relation_kg_num_interval的参数值）仍然报内存溢出的问题，请问这是怎么回事

**Comment by Paitesanshi** [comment]
@1728435673 您好，感谢您对伯乐的关注！
您能否提供更具体的信息，比如报错截图，配置文件等详细信息。

**Comment by 1728435673** [comment]
您好，我使用了伯乐库提供的数据集ml-1m，未改参数的情况下运行导致报错，报错内容如下，
参数量为：Trainable parameters: 25814208，报错内容为：
Traceback (most recent call last):
  File "E:/RecBole-master/run_recbole.py", line 48, in <module>
    run_recbole(
  File "E:\RecBole-master\recbole\quick_start\quick_start.py", line 81, in run_recbole
    flops = get_flops(model, dataset, config["device"], logger, transform)
  File "E:\RecBole-master\recbole\utils\utils.py", line 345, in get_flops
    wrapper(*inputs)
  File "D:\software\anaconda\Anaconda\envs\pyth\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\RecBole-master\recbole\utils\utils.py", line 286, in forward
    return self.model.predict(interaction)
  File "E:\RecBole-master\recbole\model\knowledge_aware_recommender\mcclk.py", line 643, in predict
    ) = self.forward()
  File "E:\RecBole-master\recbole\model\knowledge_aware_recommender\mcclk.py", line 462, in forward
    entity_gcn_emb, user_gcn_emb, item_adj = self.gcn(user_emb, entity_emb)
  File "D:\software\anaconda\Anaconda\envs\pyth\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\RecBole-master\recbole\model\knowledge_aware_recommender\mcclk.py", line 209, in forward
    item_adj = self._build_graph_separately(origin_entity_emb)
  File "E:\RecBole-master\recbole\model\knowledge_aware_recommender\mcclk.py", line 277, in _build_graph_separately
    origin_item_adj = self.build_adj(entity_emb, self.topk)
  File "E:\RecBole-master\recbole\model\knowledge_aware_recommender\mcclk.py", line 230, in build_adj
    sim = torch.mm(context_norm, context_norm.transpose(1, 0))
RuntimeError: [enforce fail at ..\c10\core\CPUAllocator.cpp:76] data. DefaultCPUAllocator: not enough memory: you tried to allo



调整以下参数：entity_kg_num_interval: "[5,inf)"       
relation_kg_num_interval: "[5,inf)"
user_inter_num_interval: "[5,inf)" 
item_inter_num_interval: "[5,inf)" 
降低了参数量，Trainable parameters: 11155648，结果仍然报内存错误not enough memory: you tried to allocate 112660922500 bytes.           我曾将relation_kg_num_interval调至[170000，inf），仍然报类似问题

请问是由于电脑配置问题无法运行吗，还是我设置的参数不准确？感谢您的回复

**Comment by Paitesanshi** [comment]
@1728435673 您好，您看起来是在CPU上运行程序，报错原因是占用内存太多，您可以尝试减小batchsize避免一次占用过多内存
