### ISSUE TITLE
[🐛BUG] 使用bert4rec模型，嵌入feature时，出现out of bounds问题

### ISSUE THREAD

**Issue by freedomSummer1964** [RUCAIBox/RecBole#1657]
**描述这个 bug**
out of bounds问题
IndexError: index 6240 is out of bounds for dimension 0 with size 6240

**如何复现**
我使用FeatureSeqEmbLayer嵌入产品特征
self.feature_embed_layer = FeatureSeqEmbLayer(
            dataset, self.embedding_size, self.selected_features, self.pooling_mode, self.device
        )
已经检查过了inter文件中的产品数量和item文件中的产品数量是相同的，不存在漏掉物品的情况，但是总是有一个物品越界
在推荐的过程中报错信息如下
Traceback (most recent call last):
  File "D:\python\mytry\pricePreference\code\runTest.py", line 69, in <module>
    run_recbole(model='BERT4Rec_new', dataset=theTheme_pu, config_file_list=[theConfigFile_pu],config_dict={'seed': 2022})
  File "D:\anaconda3\lib\site-packages\recbole\quick_start\quick_start.py", line 63, in run_recbole
    best_valid_score, best_valid_result = trainer.fit(
  File "D:\anaconda3\lib\site-packages\recbole\trainer\trainer.py", line 315, in fit
    train_loss = self._train_epoch(train_data, epoch_idx, show_progress=show_progress)
  File "D:\anaconda3\lib\site-packages\recbole\trainer\trainer.py", line 168, in _train_epoch
    losses = loss_func(interaction)
  File "D:\anaconda3\lib\site-packages\recbole\model\sequential_recommender\bert4rec_new.py", line 314, in calculate_loss
    seq_output = self.forward(user,masked_item_seq)
  File "D:\anaconda3\lib\site-packages\recbole\model\sequential_recommender\bert4rec_new.py", line 220, in forward
    sparse_embedding, dense_embedding = self.feature_embed_layer(None, item_seq)
  File "D:\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\anaconda3\lib\site-packages\recbole\model\layers.py", line 781, in forward
    return self.embed_input_fields(user_idx, item_idx)
  File "D:\anaconda3\lib\site-packages\recbole\model\layers.py", line 747, in embed_input_fields
    feature = user_item_feat[type][field_name][user_item_idx[type]]
IndexError: index 6240 is out of bounds for dimension 0 with size 6240

在其他方法，如sasrec上使用类似数据集不会出现问题，请问这是什么错误？是否因为我没有对masked item进行特征嵌入？

**Comment by chenyuwuxin** [comment]
@freedomSummer1964 您好，这个问题是由于Bert4Rec模型在实现过程中会额外增加一个item_id作为[mask] token，导致越界。

**Comment by freedomSummer1964** [comment]
> 

谢谢您的回答，那么请问我如果计划在item文件中考虑这个越界的特征，并把这个越界特征设成固定特征或者masked特征等，需要怎样在item中处理呢？我尝试在item文件中增加了一行但是无效。

**Comment by chenyuwuxin** [comment]
@freedomSummer1964 您好，通过添加物品的方式可能不会解决问题。您可以尝试手动扩充embedding table的方式来解决这个问题：
例如，将以下代码行：
https://github.com/RUCAIBox/RecBole/blob/85041a30ee7a88de6cced2763e3cb15e0f9ba8e1/recbole/model/layers.py#L928
改为：
`self.token_field_dims[type] + 1`

**Comment by freedomSummer1964** [comment]
@chenyuwuxin 您好！谢谢您的帮助，但是我使用了self.token_field_dims[type] + 1之后，显示类型不匹配，我输出了self.token_field_dims[type]，并且发现它是一个数组，我把self.token_field_dims[type] + 1改为了self.token_field_dims[type] + [1]，这样能够运行，但是out of bounds的问题仍未得到解决

**Comment by chenyuwuxin** [comment]
@freedomSummer1964 您可以尝试`list(map(lambda x: x+1, self.token_field_dims[type]))`。

**Comment by freedomSummer1964** [comment]
@chenyuwuxin 您好！我尝试了使用您的方法修改，但是IndexError: index 6240 is out of bounds for dimension 0 with size 6240的问题仍然存在，我看到如问题所示的错误报告中写道，是feature = user_item_feat[type][field_name][user_item_idx[type]]这一步出现了问题，也就是在embed_input_fields()函数当中，其中应该还未涉及到嵌入问题？
user_item_feat来自于self.dataset.get_item_feature()，而user_item_idx是索引矩阵，请问是否应该是在self.dataset.get_item_feature()这个函数中进行修改呢？

**Comment by chenyuwuxin** [comment]
@freedomSummer1964  您好，这个原因可能是修改anaconda3\lib\site-packages 库文件后，没有删除本地的__pycache__文件，导致修改没有生效。直接的做法是按照上述方法修改embedding table的大小。如果您没有用到最后的mask item，您也可以选择在代码中强制将越界的mask item(6240) 修改为 0。

**Comment by freedomSummer1964** [comment]
@chenyuwuxin 
您好！再次感谢您的回答，我继续将该语句改为self.token_embedding_table[type] = FMEmbedding(
list(map(lambda x: x+1, self.token_field_dims[type])), 
self.token_field_offsets[type], 
self.embedding_size).to(self.device)，同时删除掉了本地所有__pycache__文件，但是仍然出现了越界问题

我输出了两种方式（未改动的语句和改动后）下计算的token_embedding_table[type]
前者的形式为
FMEmbedding(
  (embedding): Embedding(8, 64)
)
后者的形式为
FMEmbedding(
  (embedding): Embedding(10, 64)
)

我再次查看了代码，feature = user_item_feat[type][field_name][user_item_idx[type]]这一步出错了，我对其中的两个元素【user_item_feat】和【user_item_idx】进行print
user_item_feat为
{'user': None, 'item': The batch_size of interaction: 1219
    item_id, torch.Size([1219]), cpu, torch.int64
    priceLevel, torch.Size([1219]), cpu, torch.int64
    ppLevel, torch.Size([1219]), cpu, torch.int64
}
user_item_idx为
{'user': None, 'item': tensor([[ 427, 1219,   70,  ...,    0,    0,    0],
        [ 220, 1219,  188,  ...,    0,    0,    0],
        [1110, 1074,  201,  ...,    0,    0,    0],
        ...,
        [1219,  205,  413,  ...,    0,    0,    0],
        [ 503,  503, 1219,  ...,    0,    0,    0],
        [ 322,   14,    0,  ...,    0,    0,    0]])}
（我的数据集有更改，现在共有1219个商品，应该是user_item_idx的[1219]对应不上）
我认为是不是user_item_feat的The batch_size of interaction: 1219变为The batch_size of interaction: 1220时，才能奏效？
我的主要问题是，请问user_item_feat里面用到的item_feat是什么形式呢，我看到源代码中是通过dataset.py的get_item_feature()函数得到了item_feat，而该函数的定义为
    def get_item_feature(self):
        """
        Returns:
            Interaction: item features
        """
        if self.item_feat is None:
            self._check_field('iid_field')
            return Interaction({self.iid_field: torch.arange(self.item_num)})
        else:
            return self.item_feat
这里是否说明还未进行到嵌入这一步，只有产品的原始特征数据，这些原始特征的tensor和user_item_idx没有对应上，导致了边界问题呢？再次感谢您的回答！

**Comment by freedomSummer1964** [comment]
@chenyuwuxin 感谢您的指导！现在代码可以正常运行了，非常感谢！
