### ISSUE TITLE
[🐛BUG] Switching eval_args mode to 'full' from 'uni100' creates error

### ISSUE THREAD

**Issue by bhuebner3** [RUCAIBox/RecBole#1658]
When using 'full' instead of 'uni100', the program gives the following error. No other settings are changed.

Traceback (most recent call last):
  File "C:\Users\Blake\OneDrive\Documents\From_Old_Comp\Vienna\Classes\Thesis\Code\RecBole-FairRec-master - Colab\run_recbole.py", line 30, in <module>
    run_recbole(model=args.model, dataset=args.dataset, config_file_list=config_file_list)
  File "C:\Users\Blake\OneDrive\Documents\From_Old_Comp\Vienna\Classes\Thesis\Code\RecBole-FairRec-master - Colab\recbole\quick_start\quick_start.py", line 56, in run_recbole
    best_valid_score, best_valid_result = trainer.fit(
  File "C:\Users\Blake\OneDrive\Documents\From_Old_Comp\Vienna\Classes\Thesis\Code\RecBole-FairRec-master - Colab\recbole\trainer\trainer.py", line 377, in fit
    valid_score, valid_result = self._valid_epoch(valid_data, show_progress=show_progress)
  File "C:\Users\Blake\OneDrive\Documents\From_Old_Comp\Vienna\Classes\Thesis\Code\RecBole-FairRec-master - Colab\recbole\trainer\trainer.py", line 217, in _valid_epoch
    valid_result = self.evaluate(valid_data, load_best_model=False, show_progress=show_progress)
  File "C:\Users\Blake\anaconda3\envs\Run_algos\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Blake\OneDrive\Documents\From_Old_Comp\Vienna\Classes\Thesis\Code\RecBole-FairRec-master - Colab\recbole\trainer\trainer.py", line 510, in evaluate
    self.eval_collector.eval_batch_collect(scores, interaction, positive_u, positive_i)
  File "C:\Users\Blake\OneDrive\Documents\From_Old_Comp\Vienna\Classes\Thesis\Code\RecBole-FairRec-master - Colab\recbole\evaluator\collector.py", line 186, in eval_batch_collect
    neg_items = interaction[self.config['ITEM_ID_FIELD']][pos_len: pos_len*2]
  File "C:\Users\Blake\OneDrive\Documents\From_Old_Comp\Vienna\Classes\Thesis\Code\RecBole-FairRec-master - Colab\recbole\data\interaction.py", line 131, in __getitem__
    return self.interaction[index]
KeyError: 'item_id'

The config file I'm using is:

ITEM_ID_FIELD: item_id
RATING_FIELD: rating
TIME_FIELD: timestamp
USER_ID_FIELD: user_id
checkpoint_dir: saved
epochs: 400
eval_args:
  group_by: user
  mode: full
  order: RO
  split:
    RS:
    - 8
    - 1
    - 1
eval_step: 1
fair_objective: value
fair_weight: -0.8
field_separator: "\t"
item_inter_num_interval: '[0,inf)'
learner: adam
learning_rate: 0.0002
load_col:
  inter:
  - user_id
  - item_id
  - rating
  - timestamp
  item:
  - item_id
  - category
  user:
  - user_id
  - gender
log_wandb: false
loss_decimal_place: 4
metric_decimal_place: 4
metrics:
- NDCG
- ShannonEntropy
- Recall
- Hit
- MRR
- DifferentialFairness
- GiniIndex
- PopularityPercentage
- ValueUnfairness
- AbsoluteUnfairness
- UnderUnfairness
- OverUnfairness
- NonParityUnfairness
reproducibility: true
save_dataset: false
seed: 1
seq_separator: ' '
show_progress: true
sst_attr_list:
- gender
stopping_step: 30
threshold:
  rating: 1.0
topk:
- 5
train_batch_size: 2048
valid_metric: NDCG@5
weight_decay: 0.0001

**Comment by peteryang1031** [comment]
Thank you for pointing out this problem. We have tested your mentioned bug and this is always occured. We have figured out the reason is that there is no specific designed code for full-sort paradigm in FairRec. We have fixed this bug and updated it in the latest version. Welcome to download it and use!
