### ISSUE TITLE
在自己的模型上训练有时会出现ValueError: Training loss is nan的问题

### ISSUE THREAD

**Issue by freedomSummer1964** [RUCAIBox/RecBole#1726]
我使用了同一种子进行处理，在自己的模型上训练，架构为图神经网络+序列推荐，这个问题有时会出现，有时则不会出现，我使用的是amazon数据集，参考了之前的issue并把max_length分别设为5和10，但是这个问题仍然时不时会出现，而且在两台机器上出现的频率不一样，另外使用srgnn等图神经网络模型，或者使用序列推荐模型运行时，该情况不会出现，请问这是机器的问题吗，因为两台机器上我都在使用cpu进行训练
具体错误信息为
Traceback (most recent call last):
  File "D:\python\mytry\multiUtility\code\main_meeting.py", line 88, in <module>
    run_recbole(model='GnnAp', dataset=theTheme_use, config_file_list=[theConfigFile],config_dict={'seed': 2006,'learning_rate': 0.005,'epochs': 100,'hidden_dropout_prob': 0.5, 'attn_dropout_prob': 0.5})
  File "D:\anaconda3\lib\site-packages\recbole\quick_start\quick_start.py", line 59, in run_recbole
    best_valid_score, best_valid_result = trainer.fit(
  File "D:\anaconda3\lib\site-packages\recbole\trainer\trainer.py", line 316, in fit
    train_loss = self._train_epoch(train_data, epoch_idx, show_progress=show_progress)
  File "D:\anaconda3\lib\site-packages\recbole\trainer\trainer.py", line 177, in _train_epoch
    self._check_nan(loss)
  File "D:\anaconda3\lib\site-packages\recbole\trainer\trainer.py", line 248, in _check_nan
    raise ValueError('Training loss is nan')
ValueError: Training loss is nan

**Comment by freedomSummer1964** [comment]
我已经解决了此问题，是因为梯度初始化不当导致的
