### ISSUE TITLE
[🐛BUG] Describe your proTraceback (most recent call last):   File "run.py", line 3, in <module>     run_recbole(model='NFM', dataset='douban')   File "D:\Download\RecBole-master\RecBole-master\recbole\quick_start\quick_start.py", line 89, in run_recbole     best_valid_score, best_valid_result = trainer.fit(   File "D:\Download\RecBole-master\RecBole-master\recbole\trainer\trainer.py", line 437, in fit     train_loss = self._train_epoch(   File "D:\Download\RecBole-master\RecBole-master\recbole\trainer\trainer.py", line 243, in _train_epoch     losses = loss_func(interaction)   File "D:\Download\RecBole-master\RecBole-master\recbole\model\context_aware_recommender\nfm.py", line 65, in calculate_loss     label = interaction[self.LABEL]   File "D:\Download\RecBole-master\RecBole-master\recbole\data\interaction.py", line 135, in __getitem__     return self.interaction[index] KeyError: 'label'blem in one sentence.

### ISSUE THREAD

**Issue by sunli-destiny** [RUCAIBox/RecBole#1790]
**Describe the bug**
环境已配置好，从git下载的源码，直接打开项目，下载了你们的数据集，运行时报错 label?
**To Reproduce**
1. extra yaml file
2. your code
3. script for running

**Expected behavior**

**Screenshots**

**Colab Links**
If applicable, add links to Colab or other Jupyter laboratory platforms that can reproduce the bug.

**Desktop (please complete the following information):**
 - OS: [e.g. Linux, macOS or Windows]
- RecBole Version [e.g. 0.1.0]
 - Python Version [e.g. 3.79]
- PyTorch Version [e.g. 1.60]
- cudatoolkit Version [e.g. 9.2, none]

**Comment by zhengbw0324** [comment]
@sunli-destiny 您好！
下载数据集后需要根据您的任务和模型配置相应参数，具体配置方法可以参考我们的[文档](https://recbole.io/docs/)。
