### ISSUE TITLE
[🐛BUG] Sequential Model Inference Problem

### ISSUE THREAD

**Issue by Woo-Yeol** [RUCAIBox/RecBole#1798]
**Describe the bug**

I'm using RecBole Framework, and in the reference function of Sequential Model, I encountered a problem in the code that converts the user-item interaction matrix to a CSR formatted matrix, and I can't proceed with the reference properly.

https://github.com/RUCAIBox/RecBole/blob/master/run_example/sequential-model-fixed-missing-last-item.ipynb

When I wrote the code to reference the model that trained the custom Movie lens dataset by referring to the above code, an error occurred because there was no item_length column.

While debugging, I found the following issues.

The code to convert the dataset object to a CSR matrix cannot be executed because the dataset object does not have a column named item_length and that column is created when proceeding with the data_prepagation() function, not create_dataset().

Also, since the output of the data_prepagation() function is a dataloader object, the function could not be executed normally.

How can we solve the following problems?

---

**Expected behavior**

If I'm approaching this the wrong way, I'd like to ask for advice, and if there's something wrong with the code, I'd like to ask for improvements.

---

**Screenshots**
```
Traceback (most recent call last):
  File "inference.py", line 64, in <module>
    prediction = generate_predict_seq(
  File "/opt/ml/input/code/level2_movierecommendation-recsys-04/utils.py", line 116, in generate_predict_seq
    temp = predict_for_all_item(user, dataset, test_data, model, config)
  File "/opt/ml/input/code/level2_movierecommendation-recsys-04/utils.py", line 40, in predict_for_all_item
    uid_series = dataset.token2id(dataset.uid_field, [external_user_id])
  File "/opt/ml/input/code/level2_movierecommendation-recsys-04/.venv/lib/python3.8/site-packages/recbole/data/dataloader/abstract_dataloader.py", line 112, in __getattribute__
    return super().__getattribute__(__name)
AttributeError: 'TrainDataLoader' object has no attribute 'token2id'
```

---

**Desktop (please complete the following information):**
- OS : Linux
python==3.8.5
torch==1.10.0
CUDA==11.0
recbole==1.1.1

**Comment by Sherry-XLL** [comment]
Hello @Woo-Yeol! Thanks for your attention to RecBole!

Generally speaking, after the dataset is processed, we will call the dataset's `inter_matrix` function to create a sparse matrix such as `coo` and `csr` as follows. At this time, the output result does not depend on the `item_length` column.

https://github.com/RUCAIBox/RecBole/blob/a757b7c31bfa407c82847b4a06c8580fa1a6b45e/recbole/model/general_recommender/lightgcn.py#L47-L48

Please provide the detailed code of the issue you mentioned so that we can better solve your problem.
