### ISSUE TITLE
[🐛BUG] 使用我自己的数据集比如ml-200k训练，修改数据集的划分方式为‘LS’和TO，出现无法识别timestamp列的问题

### ISSUE THREAD

**Issue by 437861619** [RUCAIBox/RecBole#1812]
报错信息如下：
Traceback (most recent call last):
  File "run_recbole.py", line 48, in <module>
    run_recbole(
  File "/data/fanjiaxin/Recommend/RecBole-master/recbole/quick_start/quick_start.py", line 80, in run_recbole
    train_data, valid_data, test_data = data_preparation(config, dataset)
  File "/data/fanjiaxin/Recommend/RecBole-master/recbole/data/utils.py", line 166, in data_preparation
    built_datasets = dataset.build()
  File "/data/fanjiaxin/Recommend/RecBole-master/recbole/data/dataset/dataset.py", line 1769, in build
    self.sort(by=self.time_field)
  File "/data/fanjiaxin/Recommend/RecBole-master/recbole/data/dataset/dataset.py", line 1744, in sort
    self.inter_feat.sort(by=by, ascending=ascending)
  File "/data/fanjiaxin/Recommend/RecBole-master/recbole/data/interaction.py", line 316, in sort
    raise ValueError(f"[{by}] is not exist in interaction [{self}].")
ValueError: [timestamp] is not exist in interaction [The batch_size of interaction: 100480
    user_id, torch.Size([100480]), cpu, torch.int64
    item_id, torch.Size([100480]), cpu, torch.int64
].
提示在构建交互数据集时没有找到 timestamp 列，数据集的划分方式设为‘RS’和R0没有问题，改为‘LS’和TO，利用到时间戳划分就会出现问题，是因为没有这个数据集对应的yaml文件吗，怎么解决呢

**Comment by Sherry-XLL** [comment]
您好 @437861619，之所以没有找到 `timestamp` 是因为默认的配置文件中并未加载这一列，您可以根据需要定义您自己的 yaml 文件，将其命名为 `ml-200k.yaml`，如下所示：

```yaml
load_col:
    inter: [user_id, item_id, timestamp, rating]
```

然后，使用命令 `python run_recbole.py --dataset=ml-200k --config_files=ml-200k.yaml` 即可。

其他参数配置可以参考全局配置文件 [recbole/properties/overall.yaml](https://github.com/RUCAIBox/RecBole/blob/master/recbole/properties/overall.yaml) 以及我们为 ml-100k 数据集内置的配置文件 [recbole/properties/dataset/ml-100k.yaml](https://github.com/RUCAIBox/RecBole/blob/master/recbole/properties/dataset/ml-100k.yaml)。

**Comment by 437861619** [comment]
好的，感谢！！
