### ISSUE TITLE
[🐛BUG] Evaluate时，报错另外的gpu torch.cuda.OutOfMemoryError？

### ISSUE THREAD

**Issue by KpiHang** [RUCAIBox/RecBole#1887]
**描述这个 bug**
我在 gpu_id: '1' 跑SASRec模型，训练时正常，Evaluate时，说GPU 0的显存不够。

```
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 3.46 GiB (GPU 0; 15.78 GiB total capacity; 14.62 GiB already allocated; 5.69 MiB free; 14.84 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**如何复现**
model: SASRec
dataset: yelp2022

复现这个 bug 的步骤：
1. 您引入的额外 yaml 文件
```
# environment
gpu_id: '1'
use_gpu: True 

# dataset config
field_separator: "\t"
seq_separator: " "
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating
TIME_FIELD: timestamp
NEG_PREFIX: neg_
ITEM_LIST_LENGTH_FIELD: item_length
LIST_SUFFIX: _list
MAX_ITEM_LIST_LENGTH: 50
POSITION_FIELD: position_id
load_col:
    inter: [user_id, item_id, rating, timestamp]

# data filtering for interactions
val_interval:
    rating: "[3,inf)"    
unused_col: 
    inter: [rating]

user_inter_num_interval: "[10,inf)"
item_inter_num_interval: "[10,inf)"

# training and evaluation
epochs: 200
train_batch_size: 4096
eval_batch_size: 4096000 # less one 0  because CUDA out of memory  原来是40960000 尝试减少到4096000
valid_metric: NDCG@10
eval_args:
    split: {'LS': 'valid_and_test'}
    mode: full
    order: TO

# disable negative sampling
train_neg_sample_args: ~

# model
embedding_size: 64
```
2. 您的代码

3. 您的运行脚本
`python run_recbole.py --model=SASRec --dataset=yelp2022 --config_files=./test_configs/yelp2022.yaml`

**疑问**
我尝试多个eval_batch_size：4096000、20480000、10240000、4096000
都是在 Evaluate时，报错：

```
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 3.46 GiB (GPU 0; 15.78 GiB total capacity; 14.62 GiB already allocated; 5.69 MiB free; 14.84 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```
1. 为什么报错信息中说的是GPU 0 的信息，但我明明是在gpu 1 中跑的，代码运行过程中，nvidia-smi证实是在gpu 1中运行的；
2. 为什么使用不同eval_batch_size， Evaluate时报错，Tried to allocate 3.46 GiB ，3.46这个值每种情况下都是一样的，那么，我调整eval_batch_size，似乎不太”对症下药“，这种情况下，我应该如何减少显存需求，把程序跑起来，调整另外某个参数吗?

**屏幕截图**
![image](https://github.com/RUCAIBox/RecBole/assets/70685549/60462454-65f7-41f3-a1a7-8fc716c3fa40)

**实验环境：**
 - 操作系统: [Linux]
- RecBole 1.1.1
 - Python 3.9.12
- PyTorch 2.0.1
- cudatoolkit 11.7

**额外：完整输出**

```

11 Oct 17:19    INFO  ['run_recbole.py', '--model=SASRec', '--dataset=yelp2022', '--config_files=./test_configs/yelp2022.yaml']
11 Oct 17:19    INFO  
General Hyper Parameters:
gpu_id = 1
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = dataset/yelp2022
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 200
train_batch_size = 4096
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'none', 'sample_num': 'none', 'alpha': 'none', 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'LS': 'valid_and_test'}, 'order': 'TO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = True
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = NDCG@10
valid_metric_bigger = True
eval_batch_size = 4096000
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator = 
seq_separator =  
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = {'inter': ['rating']}
additional_feat_suffix = None
rm_dup_inter = None
val_interval = {'rating': '[3,inf)'}
filter_inter_by_user_or_item = True
user_inter_num_interval = [10,inf)
item_inter_num_interval = [10,inf)
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = None
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
benchmark_filename = None

Other Hyper Parameters: 
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
n_layers = 2
n_heads = 2
hidden_size = 64
inner_size = 256
hidden_dropout_prob = 0.5
attn_dropout_prob = 0.5
hidden_act = gelu
layer_norm_eps = 1e-12
initializer_range = 0.02
loss_type = CE
numerical_features = []
discretization = None
kg_reverse_r = False
entity_kg_num_interval = [0,inf)
relation_kg_num_interval = [0,inf)
MODEL_TYPE = ModelType.SEQUENTIAL
embedding_size = 64
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cuda
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


11 Oct 17:21    INFO  yelp2022
The number of users: 72488
Average actions of users: 28.18990991488129
The number of items: 43749
Average actions of items: 46.708466672762185
The number of inters: 2043402
The sparsity of the dataset: 99.9355653362953%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
11 Oct 17:24    INFO  [Training]: train_batch_size = [4096] train_neg_sample_args: [{'distribution': 'none', 'sample_num': 'none', 'alpha': 'none', 'dynamic': False, 'candidate_num': 0}]
11 Oct 17:24    INFO  [Evaluation]: eval_batch_size = [4096000] eval_args: [{'split': {'LS': 'valid_and_test'}, 'order': 'TO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
11 Oct 17:24    INFO  SASRec(
  (item_embedding): Embedding(43749, 64, padding_idx=0)
  (position_embedding): Embedding(50, 64)
  (trm_encoder): TransformerEncoder(
    (layer): ModuleList(
      (0-1): 2 x TransformerLayer(
        (multi_head_attention): MultiHeadAttention(
          (query): Linear(in_features=64, out_features=64, bias=True)
          (key): Linear(in_features=64, out_features=64, bias=True)
          (value): Linear(in_features=64, out_features=64, bias=True)
          (softmax): Softmax(dim=-1)
          (attn_dropout): Dropout(p=0.5, inplace=False)
          (dense): Linear(in_features=64, out_features=64, bias=True)
          (LayerNorm): LayerNorm((64,), eps=1e-12, elementwise_affine=True)
          (out_dropout): Dropout(p=0.5, inplace=False)
        )
        (feed_forward): FeedForward(
          (dense_1): Linear(in_features=64, out_features=256, bias=True)
          (dense_2): Linear(in_features=256, out_features=64, bias=True)
          (LayerNorm): LayerNorm((64,), eps=1e-12, elementwise_affine=True)
          (dropout): Dropout(p=0.5, inplace=False)
        )
      )
    )
  )
  (LayerNorm): LayerNorm((64,), eps=1e-12, elementwise_affine=True)
  (dropout): Dropout(p=0.5, inplace=False)
  (loss_fct): CrossEntropyLoss()
)
Trainable parameters: 2903232
11 Oct 17:24    INFO  FLOPs: 4983464.0
Train     0: 100%|███████████████████████| 446/446 [01:53<00:00,  3.93it/s, GPU RAM: 6.13 G/15.78 G]
11 Oct 17:25    INFO  epoch 0 training [time: 113.58s, train loss: 4320.5268]
Evaluate   :   0%|                                                            | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/data/xxx/RecBole/run_recbole.py", line 48, in <module>
    run_recbole(
  File "/data/xxx/RecBole/recbole/quick_start/quick_start.py", line 89, in run_recbole
    best_valid_score, best_valid_result = trainer.fit(
  File "/data/xxx/RecBole/recbole/trainer/trainer.py", line 462, in fit
    valid_score, valid_result = self._valid_epoch(
  File "/data/xxx/RecBole/recbole/trainer/trainer.py", line 281, in _valid_epoch
    valid_result = self.evaluate(
  File "/data/xxx/anaconda3/envs/ALL/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/xxx/RecBole/recbole/trainer/trainer.py", line 614, in evaluate
    interaction, scores, positive_u, positive_i = eval_func(batched_data)
  File "/data/xxx/RecBole/recbole/trainer/trainer.py", line 523, in _full_sort_batch_eval
    scores = self.model.full_sort_predict(interaction.to(self.device))
  File "/data/xxx/RecBole/recbole/model/sequential_recommender/sasrec.py", line 147, in full_sort_predict
    seq_output = self.forward(item_seq, item_seq_len)
  File "/data/xxx/RecBole/recbole/model/sequential_recommender/sasrec.py", line 109, in forward
    trm_output = self.trm_encoder(
  File "/data/xxx/anaconda3/envs/ALL/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/xxx/RecBole/recbole/model/layers.py", line 625, in forward
    hidden_states = layer_module(hidden_states, attention_mask)
  File "/data/xxx/anaconda3/envs/ALL/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/xxx/RecBole/recbole/model/layers.py", line 568, in forward
    feedforward_output = self.feed_forward(attention_output)
  File "/data/xxx/anaconda3/envs/ALL/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/xxx/RecBole/recbole/model/layers.py", line 521, in forward
    hidden_states = self.intermediate_act_fn(hidden_states)
  File "/data/xxx/RecBole/recbole/model/layers.py", line 514, in gelu
    return x * 0.5 * (1.0 + torch.erf(x / math.sqrt(2.0)))
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 3.46 GiB (GPU 0; 15.78 GiB total capacity; 14.62 GiB already allocated; 5.69 MiB free; 14.84 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by Yilu114** [comment]
1. 为什么报告 GPU 0 的错误？
虽然设置了 gpu_id: '1' 以在 GPU 1 上运行，但这不意味着 PyTorch 不会与其他 GPU 交互。PyTorch 默认会检查所有可用的 GPU，包括 GPU 0。当 GPU 0 的显存不足时，即使你的主要运算在 GPU 1 上进行，它仍然会报错。

2. 为什么 eval_batch_size 调整后，所需的显存大小保持不变？
这个问题的关键在于你正在使用的模型的推理方式。SASRec 模型在评估阶段使用全排序评估方法。这意味着对于每个用户，模型都会为所有的项目生成一个分数，这对显存的需求是巨大的。因此，调整 eval_batch_size 对显存的总体需求几乎没有影响。

可能的解决方案：
为了确保 PyTorch 仅使用 GPU 1 并完全忽略 GPU 0，你可以设置 CUDA 设备可见性。具体来说，你可以在运行你的脚本之前设置 `CUDA_VISIBLE_DEVICES` 环境变量。

方法如下：

1. **命令行设置**：
在运行你的脚本之前，首先设置 `CUDA_VISIBLE_DEVICES`：

```bash
export CUDA_VISIBLE_DEVICES=1
python run_recbole.py --model=SASRec --dataset=yelp2022 --config_files=./test_configs/yelp2022.yaml
```

2. **在 Python 脚本中设置**：
你也可以在 Python 脚本的开头设置此环境变量：

```python
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "1"
```

注意：当你设置 `CUDA_VISIBLE_DEVICES=1` 时，PyTorch 将只看到一个 GPU（即 GPU 1），并认为它是 GPU 0。因此，在你的代码中，当你将 Tensor 移到 GPU 上时，你应该使用 `device='cuda:0'`，尽管实际上它是在 GPU 1 上运行的。

最后，虽然不是一个实际的解决方案，但如果可能的话，考虑升级到具有更大显存的 GPU。这将为更大、更复杂的模型提供更大的容量。

**Comment by KpiHang** [comment]
感谢，您的回答足够详细，受益良多。
