### ISSUE TITLE
[🐛BUG] 在运行NCL模型的时候报错。

### ISSUE THREAD

**Issue by YukinoAsuna** [RUCAIBox/RecBole#1957]
**描述这个 bug**
当我在运行python run.py  --dataset=ml-100k --model=NCL（ run.py 文件就如同你们介绍的那样只包含run_rebole() )报告了如下错误。

Traceback (most recent call last):
  File "/home/zxweng/recommender/run.py", line 2, in <module>
    run_recbole()
  File "/home/zxweng/anaconda3/envs/wzx/lib/python3.9/site-packages/recbole/quick_start/quick_start.py", line 148, in run_recbole
    best_valid_score, best_valid_result = trainer.fit(
  File "/home/zxweng/anaconda3/envs/wzx/lib/python3.9/site-packages/recbole/trainer/trainer.py", line 1327, in fit
    self.model.e_step()
  File "/home/zxweng/anaconda3/envs/wzx/lib/python3.9/site-packages/recbole/model/general_recommender/ncl.py", line 81, in e_step
    self.user_centroids, self.user_2cluster = self.run_kmeans(user_embeddings)
  File "/home/zxweng/anaconda3/envs/wzx/lib/python3.9/site-packages/recbole/model/general_recommender/ncl.py", line 89, in run_kmeans
    kmeans.train(x)
  File "/home/zxweng/anaconda3/envs/wzx/lib/python3.9/site-packages/faiss/extra_wrappers.py", line 329, in train
    clus.train(x, self.index, weights)
  File "/home/zxweng/anaconda3/envs/wzx/lib/python3.9/site-packages/faiss/class_wrappers.py", line 85, in replacement_train
    self.train_c(n, swig_ptr(x), index)
  File "/home/zxweng/anaconda3/envs/wzx/lib/python3.9/site-packages/faiss/swigfaiss_avx2.py", line 2560, in train
    return _swigfaiss_avx2.Clustering_train(self, n, x, index, x_weights)
RuntimeError: Error in void faiss::Clustering::train_encoded(faiss::Clustering::idx_t, const uint8_t*, const faiss::Index*, faiss::Index&, const float*) at /root/miniconda3/conda-bld/faiss-pkg_1669821591485/work/faiss/Clustering.cpp:283: Error: 'nx >= k' failed: Number of training points (944) should be at least as large as number of clusters (1000)

**如何复现**
不用修改任何代码直接运行

**预期**
对您的预期作清晰简明的描述。

**屏幕截图**
添加屏幕截图以帮助解释您的问题。（可选）

**链接**
添加能够复现 bug 的代码链接，如 Colab 或者其他在线 Jupyter 平台。（可选）

**实验环境（请补全下列信息）：**
 - 操作系统: Linux
- RecBole 版本 1.2.0
 - Python 版本 3.9.12
- PyTorch 版本 1.13.1+cu116
- cudatoolkit 版本 11.3

**Comment by TayTroye** [comment]
@YukinoAsuna 
Hello,the number of training points should be at least as large as number of clusters.You can set the `num_clusters` less than trainng points.
