### ISSUE TITLE
torch.distributed.DistBackendError: [5] is setting up NCCL communicator and retrieving ncclUniqueId from [0] via c10d key-value store by key '0', but store->get('0') got error: Socket Timeout

### ISSUE THREAD

**Issue by zw81929** [RUCAIBox/RecBole#2069]
Python 3.11.9  OS :UBUNTU 24.04 LTS

包：
bole                      0.0.13
kmeans-pytorch            0.3
torch                     2.3.1+cu121
torchaudio                2.3.1+cu121
torchvision               0.18.1+cu121
nvidia-cuda-cupti-cu12    12.1.105
nvidia-cuda-nvrtc-cu12    12.1.105
nvidia-cuda-runtime-cu12  12.1.105
nvidia-nccl-cu12          2.20.5

始终出现这个报错：
**torch.distributed.DistBackendError: [5] is setting up NCCL communicator and retrieving ncclUniqueId from [0] via c10d key-value store by key '0', but store->get('0') got error: Socket Timeout**

```
[rank5]:[W socket.cpp:432] [c10d] While waitForInput, poolFD failed with (errno: 0 - Success).
W0719 18:42:55.168000 131513588901696 torch/multiprocessing/spawn.py:145] Terminating process 25364 via signal SIGTERM
W0719 18:43:03.904000 131513588901696 torch/multiprocessing/spawn.py:145] Terminating process 25365 via signal SIGTERM
W0719 18:43:03.905000 131513588901696 torch/multiprocessing/spawn.py:145] Terminating process 25366 via signal SIGTERM
W0719 18:43:03.906000 131513588901696 torch/multiprocessing/spawn.py:145] Terminating process 25367 via signal SIGTERM
W0719 18:43:03.907000 131513588901696 torch/multiprocessing/spawn.py:145] Terminating process 25368 via signal SIGTERM
W0719 18:43:34.059000 131513588901696 torch/multiprocessing/spawn.py:153] Unable to shutdown process 25364 via SIGTERM , forcefully exiting via SIGKILL
Traceback (most recent call last):
  File "/data1/bert4rec/bert4rec-main/scripts/bole/run_a.py", line 52, in <module>
    mp.spawn(
  File "/data1/bert4rec/bert4rec-main/venv/lib/python3.11/site-packages/torch/multiprocessing/spawn.py", line 281, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method="spawn")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/bert4rec/bert4rec-main/venv/lib/python3.11/site-packages/torch/multiprocessing/spawn.py", line 237, in start_processes
    while not context.join():
              ^^^^^^^^^^^^^^
  File "/data1/bert4rec/bert4rec-main/venv/lib/python3.11/site-packages/torch/multiprocessing/spawn.py", line 188, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 5 terminated with the following error:
Traceback (most recent call last):
  File "/data1/bert4rec/bert4rec-main/venv/lib/python3.11/site-packages/torch/multiprocessing/spawn.py", line 75, in _wrap
    fn(i, *args)
  File "/data1/bert4rec/bert4rec-main/scripts/bole/recbole/quick_start/quick_start.py", line 190, in run_recboles
    run_recbole(
  File "/data1/bert4rec/bert4rec-main/scripts/bole/recbole/quick_start/quick_start.py", line 145, in run_recbole
    trainer = get_trainer(config["MODEL_TYPE"], config["model"])(config, model)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/bert4rec/bert4rec-main/scripts/bole/recbole/trainer/trainer.py", line 112, in __init__
    super(Trainer, self).__init__(config, model)
  File "/data1/bert4rec/bert4rec-main/scripts/bole/recbole/trainer/trainer.py", line 62, in __init__
    self.distributed_model = DistributedDataParallel(
                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/bert4rec/bert4rec-main/venv/lib/python3.11/site-packages/torch/nn/parallel/distributed.py", line 798, in __init__
    _verify_param_shape_across_processes(self.process_group, parameters)
  File "/data1/bert4rec/bert4rec-main/venv/lib/python3.11/site-packages/torch/distributed/utils.py", line 269, in _verify_param_shape_across_processes
    return dist._verify_params_across_processes(process_group, tensors, logger)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.distributed.DistBackendError: [5] is setting up NCCL communicator and retrieving ncclUniqueId from [0] via c10d key-value store by key '0', but store->get('0') got error: Socket Timeout
Exception raised from doWait at ../torch/csrc/distributed/c10d/TCPStore.cpp:563 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7b61e2c83897 in /data1/bert4rec/bert4rec-main/venv/lib/python3.11/site-packages/torch/lib/libc10.so)



```

**Comment by zw81929** [comment]
自己挖的坑自己解决：
1、我的数据集非常大，启动的时候1T内存是不够的，因此启用了swap。而且swapfile是放在一个iscsi上，swapfile大小是1T。
2、单服务多卡模式，6个A10，每个24G。
以上为背景
解决方法：
1、测试发现5块卡可以跑起来。怀疑ddp因为启动的时候记载模型都在一个gpu造成，因此调整了batchsize，缩减后6块都可以
2、在服务器又配置两块硬盘，swapfile放到本地硬盘上了，问题也不再发生。
关键还是得多看看ddp原理
