### ISSUE TITLE
LightGCN and MF model are not working

### ISSUE THREAD

**Issue by emrulhasan-nlp** [RUCAIBox/RecBole#2090]
**Describe the bug**
I am trying to run some models. I have been able to successfully run ItemkNN, SLIMElastic, and BPR. However, when I want to run for LightGCN, it give the following error. 

Error: 
** Traceback (most recent call last):
  File "/content/RecBole/run_recbole.py", line 46, in <module>
    run(
  File "/content/RecBole/recbole/quick_start/quick_start.py", line 52, in run
    res = run_recbole(
  File "/content/RecBole/recbole/quick_start/quick_start.py", line 137, in run_recbole
    model = get_model(config["model"])(config, train_data._dataset).to(config["device"])
  File "/content/RecBole/recbole/model/general_recommender/lightgcn.py", line 76, in __init__
    self.norm_adj_matrix = self.get_norm_adj_mat().to(self.device)
  File "/content/RecBole/recbole/model/general_recommender/lightgcn.py", line 111, in get_norm_adj_mat
    A._update(data_dict)
AttributeError: 'dok_matrix' object has no attribute '_update'. Did you mean: 'update'?**

similarly for MF, I get the following error:
Error:
**ValueError: `model_name` [MF] is not the name of an existing model.**

Attached screenshot for both the errors. Thanks in advance
![LightGCN](https://github.com/user-attachments/assets/9b378da8-24a6-4145-ae2f-74217775bf4c)
![MF](https://github.com/user-attachments/assets/53c52b1f-fe13-4861-b1ce-e6808615dd38)

**Comment by downeykking** [comment]
In Spicy, dok_matrix no longer allows update.
You can change the code
```
A._update(data_dict)
```
to
```
for (row, col), value in data_dict.items():
    A[row, col] = value
```
which directly assigns values to A from data_dict.

**Comment by xxx08796** [comment]
ran into the same problem, a fix would be great
