### ISSUE TITLE
[🐛BUG] 用一句话描述您的问题。

### ISSUE THREAD

**Issue by lovedididi** [RUCAIBox/RecBole#2104]
Traceback (most recent call last):
  File "/home/yy/FDSA/RecBole-master/run_recbole.py", line 51, in <module>
    run(
  File "/home/yy/FDSA/RecBole-master/recbole/quick_start/quick_start.py", line 52, in run
    res = run_recbole(
  File "/home/yy/FDSA/RecBole-master/recbole/quick_start/quick_start.py", line 141, in run_recbole
    flops = get_flops(model, dataset, config["device"], logger, transform)
  File "/home/yy/FDSA/RecBole-master/recbole/utils/utils.py", line 347, in get_flops
    wrapper(*inputs)
  File "/home/yy/.conda/envs/recbole/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/yy/.conda/envs/recbole/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/yy/FDSA/RecBole-master/recbole/utils/utils.py", line 288, in forward
    return self.model.predict(interaction)
  File "/home/yy/FDSA/RecBole-master/recbole/model/sequential_recommender/sasrecf.py", line 173, in predict
    seq_output = self.forward(item_seq, item_seq_len)
  File "/home/yy/FDSA/RecBole-master/recbole/model/sequential_recommender/sasrecf.py", line 137, in forward
    input_emb = self.concat_layer(input_concat)
  File "/home/yy/.conda/envs/recbole/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/yy/.conda/envs/recbole/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1582, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/yy/.conda/envs/recbole/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 116, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (50x384 and 448x64)
请问，出现这种情况是SASRecF需要配置一些别的参数吗？

**Comment by yptu106** [comment]
I ran into the same issue when adding an item embedding as a `float_seq` additional feature column. 

I appended `side_emb:float_seq` (a 384-d vector) to the `.item` file and enabled it via:
```yaml
load_col:
  item: [streamer_id, side_emb]
numerical_features: [side_emb]
selected_features: [side_emb]
hidden_size: 64
field_separator: "\t"
seq_separator: " "
```

At runtime, `FeatureSeqEmbLayer` returns:
```
dense_embedding.shape == (B, L, 1, 64) # one pooled group
```
and my forward concatenates `[item_emb(64), feature_emb(64)] -> (B, L, 128)`. 

However, in `__init__`, SASRecF computes:
```python
num_feature_field = sum(1 if fieldtype != FLOAT_SEQ else dataset.num(field) ...)
```
For `float_seq`, `dataset.num(field)` effectively becomes 2 because each row is stored as a tuple `(values, weights)`. That inflates `num_feature_field` to 2 and builds:
```
concat_layer.in_features = 64 * (1 + 2) = 192
```

which yields the similar mismatch: 
```
RuntimeError: mat1 and mat2 shapes cannot be multiplied (... x 128 and 192 x 64)
```

### Minimal fix that worked for me
Treat each selected side feature as one pooled group:
```python
# SASRecF.__init__
self.num_feature_field = len(self.selected_features)
self.concat_layer = nn.Linear(self.hidden_size * (1 + self.num_feature_field),
                              self.hidden_size)
```

Does this understanding look correct? If so, I’m happy to open a PR with this change.
