### ISSUE TITLE
[🐛BUG] 在0.2.0版本的源码中，没有找到recbole.model.exlib_recommender

### ISSUE THREAD

**Issue by dxjjhm** [RUCAIBox/RecBole#689]
从pypi.org下载0.2.0版本的源码，运行bpr, ml100k时，报错
Traceback (most recent call last):
  File "D:/source/recbole-0.2.0/app/ex/bpr_ml100k.py", line 16, in <module>
    main()
  File "D:/source/recbole-0.2.0/app/ex/bpr_ml100k.py", line 12, in main
    config_dict=param_dict)
  File "D:\source\recbole-0.2.0\recbole\quick_start\quick_start.py", line 29, in run_recbole
    config = Config(model=model, dataset=dataset, config_file_list=config_file_list, config_dict=config_dict)
  File "D:\source\recbole-0.2.0\recbole\config\configurator.py", line 75, in __init__
    self.model, self.model_class, self.dataset = self._get_model_and_dataset(model, dataset)
  File "D:\source\recbole-0.2.0\recbole\config\configurator.py", line 187, in _get_model_and_dataset
    final_model_class = get_model(final_model)
  File "D:\source\recbole-0.2.0\recbole\utils\utils.py", line 63, in get_model
    if importlib.util.find_spec(module_path, __name__):
  File "D:\Anaconda3\envs\pytorch\lib\importlib\util.py", line 94, in find_spec
    parent = __import__(parent_name, fromlist=['__path__'])
ModuleNotFoundError: No module named 'recbole.model.exlib_recommender'

**Comment by 2017pxy** [comment]
@dxjjhm 你好，我刚刚在linux和Windows上都通过pip install 安装了recbole并运行bpr, ml100k，都是正常运行的；没能成功复现你的情况；
我的代码如下
run.py文件：
```
from recbole.quick_start import run_recbole
run_recbole()
```
命令行：
`python run.py --dataset=ml-100k --model=BPR`

请你提供更详细的信息，以便我们帮你解决你的问题，谢谢！

**Comment by dxjjhm** [comment]
原因应该是我这边model名称写错了，然后get_model方法去加载了extlib_recommender, 这时报错了，已找到原因，感谢。
