### ISSUE TITLE
[🐛BUG] KeyError: 'label' and AttributeError raises for some datasets

### ISSUE THREAD

**Issue by GYHHAHA** [RUCAIBox/RecBole#776]
For `ml-20m`, this raises.
```
>>>python run.py --dataset=ml-20m --model=FM
......
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    run_recbole()
  File "/home/gyh/anaconda3/envs/NN/lib/python3.8/site-packages/recbole/quick_start/quick_start.py", line 53, in run_recbole
    best_valid_score, best_valid_result = trainer.fit(
  File "/home/gyh/anaconda3/envs/NN/lib/python3.8/site-packages/recbole/trainer/trainer.py", line 262, in fit
    train_loss = self._train_epoch(train_data, epoch_idx, show_progress=show_progress)
  File "/home/gyh/anaconda3/envs/NN/lib/python3.8/site-packages/recbole/trainer/trainer.py", line 152, in _train_epoch
    losses = loss_func(interaction)
  File "/home/gyh/anaconda3/envs/NN/lib/python3.8/site-packages/recbole/model/context_aware_recommender/fm.py", line 53, in calculate_loss
    label = interaction[self.LABEL]
  File "/home/gyh/anaconda3/envs/NN/lib/python3.8/site-packages/recbole/data/interaction.py", line 105, in __getitem__
    return self.interaction[index]
KeyError: 'label'
```
For Criteo, this raises,
```
>>>python run.py --dataset=Criteo --model=FM
...
22 Mar 16:46    WARNING No columns has been loaded from [FeatureSource.INTERACTION]
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    run_recbole()
  File "/home/gyh/anaconda3/envs/NN/lib/python3.8/site-packages/recbole/quick_start/quick_start.py", line 39, in run_recbole
    dataset = create_dataset(config)
  File "/home/gyh/anaconda3/envs/NN/lib/python3.8/site-packages/recbole/data/utils.py", line 53, in create_dataset
    return Dataset(config)
  File "/home/gyh/anaconda3/envs/NN/lib/python3.8/site-packages/recbole/data/dataset/dataset.py", line 100, in __init__
    self._from_scratch()
  File "/home/gyh/anaconda3/envs/NN/lib/python3.8/site-packages/recbole/data/dataset/dataset.py", line 113, in _from_scratch
    self._data_processing()
  File "/home/gyh/anaconda3/envs/NN/lib/python3.8/site-packages/recbole/data/dataset/dataset.py", line 156, in _data_processing
    self._data_filtering()
  File "/home/gyh/anaconda3/envs/NN/lib/python3.8/site-packages/recbole/data/dataset/dataset.py", line 178, in _data_filtering
    self._filter_nan_user_or_item()
  File "/home/gyh/anaconda3/envs/NN/lib/python3.8/site-packages/recbole/data/dataset/dataset.py", line 604, in _filter_nan_user_or_item
    dropped_inter = self.inter_feat.index[self.inter_feat[field].isnull()]
AttributeError: 'NoneType' object has no attribute 'index'
```
I directly download the atomic files from baidu cloud desk and put these datasets at the legal path.
Wondering how to fix this. Thanks!

**Comment by GYHHAHA** [comment]
I believe the inter_feat refers to a pandas DataFrame or Series, but why this value assigned to None instead of a pd Type? Confused.

**Comment by chenyushuo** [comment]
Have you set `threshold`? This parameter is used to generate `label`, which is necessary for context-aware model. About `threshold`, take the following example:

```yaml
threshold: {'rating': 4}
```

This means the `label` of interaction is set to 1 if its `rating` is greater or equal to 4, otherwise, the `label` is 0.

**Comment by GYHHAHA** [comment]
Thanks for your reply! And I have another question: how to change atomic file to regular csv/tsv file?

**Comment by hyp1231** [comment]
The atomic files are just regular text files.

If you use atomic files provided by us, they are tsv files defaultly. Replacing all `\t` to `,` then you can get csv files.

**Comment by GYHHAHA** [comment]
Thanks so much!
