### ISSUE TITLE
[🐛BUG] User and Item atomic files cannot have same feature names

### ISSUE THREAD

**Issue by khajaphysist** [RUCAIBox/RecBole#826]
When `.user` and `.item` files have features with same name, following error will occur

```
Traceback (most recent call last):
  File "run.py", line 4, in <module>
    run_recbole(model="FM", dataset="anon", config_file_list=["anon.yaml"], saved=False, config_dict={"data_path": "./dataset"})
  File "/Users/xxxxxxxxx/miniconda3/envs/test/lib/python3.8/site-packages/recbole/quick_start/quick_start.py", line 39, in run_recbole
    dataset = create_dataset(config)
  File "/Users/xxxxxxxxx/miniconda3/envs/test/lib/python3.8/site-packages/recbole/data/utils.py", line 53, in create_dataset
    return Dataset(config)
  File "/Users/xxxxxxxxx/miniconda3/envs/test/lib/python3.8/site-packages/recbole/data/dataset/dataset.py", line 100, in __init__
    self._from_scratch()
  File "/Users/xxxxxxxxx/miniconda3/envs/test/lib/python3.8/site-packages/recbole/data/dataset/dataset.py", line 114, in _from_scratch
    self._change_feat_format()
  File "/Users/xxxxxxxxx/miniconda3/envs/test/lib/python3.8/site-packages/recbole/data/dataset/dataset.py", line 964, in _change_feat_format
    setattr(self, feat_name, self._dataframe_to_interaction(feat))
  File "/Users/xxxxxxxxx/miniconda3/envs/test/lib/python3.8/site-packages/recbole/data/dataset/dataset.py", line 1704, in _dataframe_to_interaction
    new_data[k] = torch.LongTensor(value)
TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.
```

**Comment by 2017pxy** [comment]
@khajaphysist Hi, firstly thanks for pointing out this problem.

When we designed the atomic file, we think it might be confused for models if two files have the same feature, so it's true that different atomic files can not have same feature name. We are sorry that we dont't mention this point in our docs and the error message is unclear. 

If you want to load same feature from two different files, you can just rename the feature like 'FEATURE_in_user' and 'FEATURE_in_item', then you can successfully load these features. (Although I don't know why you want to load the same feature twice from different files). 

Finally, thanks for your bug report and we will add this point in our docs and make our error message more clear!

**Comment by khajaphysist** [comment]
@2017pxy Thanks for the clarification. I have solved it as you suggested.
