### ISSUE TITLE
[BUG]LightGBM 训练错误(数据集加载)

### ISSUE THREAD

**Issue by metio-zijun** [RUCAIBox/RecBole#836]
使用lightgbm模型训练的时候，在读取数据时候发生错误
在DecisionTreeTrainer的_interaction_to_sparse函数中   interaction = dataloader.dataset[:]这个有问题
只能读取到user和item，　并不能读取到label，dataset中应该是没有包含label 的

Traceback (most recent call last):
  File "/home/metio/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-620462efd75b>", line 6, in <module>
    train_data, valid_data, saved=saved, show_progress=config['show_progress']
  File "/home/metio/anaconda3/lib/python3.7/site-packages/recbole/trainer/trainer.py", line 707, in fit
    self._train_at_once(train_data, valid_data)
  File "/home/metio/anaconda3/lib/python3.7/site-packages/recbole/trainer/trainer.py", line 904, in _train_at_once
    self.dtrain = self._interaction_to_lib_datatype(train_data)
  File "/home/metio/anaconda3/lib/python3.7/site-packages/recbole/trainer/trainer.py", line 894, in _interaction_to_lib_datatype
    data, label = self._interaction_to_sparse(dataloader)
  File "/home/metio/anaconda3/lib/python3.7/site-packages/recbole/trainer/trainer.py", line 683, in _interaction_to_sparse
    return cur_data, interaction_np[self.label_field]
KeyError: 'label'

**Comment by flust** [comment]
@metio-zijun 你好，想先确认一下你的原始数据是有label_field的吗？如果原始数据没有label的话这个是跑不了的

**Comment by tsotfsk** [comment]
可以查看一下配置文件总是否有指定label的域，我们默认的label域叫`label`，如果你使用其它的名字，应当做相应修改
```json
LABEL_FIELD: label
```

**Comment by metio-zijun** [comment]
> @metio-zijun 你好，想先确认一下你的原始数据是有label_field的吗？如果原始数据没有label的话这个是跑不了的

我的数据中没有label这个 ，这个label列不应该是制作数据集时候自己采样生成的吗？在其他模型都是这样的

**Comment by flust** [comment]
> > @metio-zijun 你好，想先确认一下你的原始数据是有label_field的吗？如果原始数据没有label的话这个是跑不了的
> 
> 我的数据中没有label这个 ，这个label列不应该是制作数据集时候自己采样生成的吗？在其他模型都是这样的

目前lightgbm实现的还只支持自带label域的数据，后续我们会考虑再进行修改
