### ISSUE TITLE
get_model 后，是否需要设置模型的device ? 

### ISSUE THREAD

**Issue by dxjjhm** [RUCAIBox/RecBole#837]
```python3
#!/usr/bin/env python
# coding: utf-8

import pickle
import torch
from recbole.config import Config
from recbole.data import create_dataset, data_preparation, save_split_dataloaders, load_split_dataloaders
from recbole.utils import init_seed, init_logger, get_model, get_trainer
from recbole.utils.case_study import full_sort_topk, full_sort_scores

bpr_model_path = "/data/home/recbole/general/saved/sdyd/bpr/2/BPR-May-25-2021_14-42-59.pth"
bpr_data_path = "/data/home/recbole/general/saved/sdyd/bpr/2/sdyd-dataset.pth"
bpr_data_split_path = "/data/home/recbole/general/saved/sdyd/bpr/2/sdyd-for-BPR-dataloader.pth"

param_dict = {
    "gpu_id": 1, 
    "use_gpu": True
}

config = Config(model='BPR', dataset='sdyd', 
                config_file_list=['/data/home/recbole/properties/bpr.sdyd2.yaml'],
                config_dict=param_dict)

print(config)
init_seed(config['seed'], config['reproducibility'])
init_logger(config)

with open(bpr_data_path, 'rb') as f:
    dataset = pickle.load(f)
print(dataset)
train_data, valid_data, test_data = load_split_dataloaders(bpr_data_split_path)
model = get_model(config['model'])(config, train_data).to(config['device'])
checkpoint = torch.load(bpr_model_path)
model.load_state_dict(checkpoint['state_dict'])
model.eval()
print(model)

uid_series = dataset.token2id(dataset.uid_field, ['200', '201'])
topk_score, topk_iid_list = full_sort_topk(uid_series, model, test_data, k=20)
```
**最后预测爆出如下错误**

```
Traceback (most recent call last):
  File "bpr_predict.py", line 62, in <module>
    topk_score, topk_iid_list = full_sort_topk(uid_series, model, test_data, k=20)
  File "/data/home/anaconda3/envs/pytorch/lib/python3.7/site-packages/recbole-0.2.1-py3.7.egg/recbole/utils/case_study.py", line 87, in full_sort_topk
    scores = full_sort_scores(uid_series, model, test_data)
  File "/data/home/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/data/home/anaconda3/envs/pytorch/lib/python3.7/site-packages/recbole-0.2.1-py3.7.egg/recbole/utils/case_study.py", line 59, in full_sort_scores
    scores = model.full_sort_predict(input_interaction)
  File "/data/home/anaconda3/envs/pytorch/lib/python3.7/site-packages/recbole-0.2.1-py3.7.egg/recbole/model/general_recommender/bpr.py", line 93, in full_sort_predict
    user_e = self.get_user_embedding(user)
  File "/data/home/anaconda3/envs/pytorch/lib/python3.7/site-packages/recbole-0.2.1-py3.7.egg/recbole/model/general_recommender/bpr.py", line 56, in get_user_embedding
    return self.user_embedding(user)
  File "/data/home/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/home/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/sparse.py", line 126, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "/data/home/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py", line 1852, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Input, output and indices must be on the current device
```

**Comment by dxjjhm** [comment]
从源代码没有看出需要设置 tensor 放到哪一个 device，请协助看下

**Comment by dxjjhm** [comment]
在获取模型是显示的设置device是个bug, 去除后可以正常运行
model = get_model(config['model'])(config, train_data).to(config['device'])
改成   model = get_model(config['model'])(config, train_data)

**但是， test_data.user_df.interactioni[dataset.uid_field] 的device 的确是cpu, 然后模型加载是在gpu, 到时谁是谁的bug?**

**Comment by 2017pxy** [comment]
@dxjjhm 你好，某些模型的参数是存在GPU上的，这可能导致模型参数和数据不在同一个设备上的bug，因此需要根据报错信息进行代码的手动调整，我们给出的case_study_example.py只是一个例子，不能保证覆盖所有情况，我们之后也会针对这个问题进行优化，感谢你的反馈！
