### ISSUE TITLE
Returning Error while creating AFM Model

### ISSUE THREAD

**Issue by iamharikrishnank** [RUCAIBox/RecBole#988]
when creating AFM model this error occurs
scores = self.model.full_sort_predict(interaction.to(self.device))
File "/home/harikrishnan/Downloads/recbole_latest/RecBole/recbole/model/abstract_recommender.py", line 66, in full_sort_predict
raise NotImplementedError
NotImplementedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "run_recbole.py", line 25, in
run_recbole(model=args.model, dataset=args.dataset, config_file_list=config_file_list)
File "/home/harikrishnan/Downloads/recbole_latest/RecBole/recbole/quick_start/quick_start.py", line 60, in run_recbole
train_data, valid_data, saved=saved, show_progress=config['show_progress']
File "/home/harikrishnan/Downloads/recbole_latest/RecBole/recbole/trainer/trainer.py", line 334, in fit
valid_score, valid_result = self._valid_epoch(valid_data, show_progress=show_progress)
File "/home/harikrishnan/Downloads/recbole_latest/RecBole/recbole/trainer/trainer.py", line 196, in _valid_epoch
valid_result = self.evaluate(valid_data, load_best_model=False, show_progress=show_progress)
File "/home/harikrishnan/Downloads/recbole_latest/RecBole/env/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
return func(*args, **kwargs)
File "/home/harikrishnan/Downloads/recbole_latest/RecBole/recbole/trainer/trainer.py", line 459, in evaluate
interaction, scores, positive_u, positive_i = eval_func(batched_data)
File "/home/harikrishnan/Downloads/recbole_latest/RecBole/recbole/trainer/trainer.py", line 383, in _full_sort_batch_eval
scores = self.model.predict(new_inter)
File "/home/harikrishnan/Downloads/recbole_latest/RecBole/recbole/model/context_aware_recommender/afm.py", line 115, in predict
return self.forward(interaction)
File "/home/harikrishnan/Downloads/recbole_latest/RecBole/recbole/model/context_aware_recommender/afm.py", line 102, in forward
afm_all_embeddings = self.concat_embed_input_fields(interaction) # [batch_size, num_field, embed_dim]
File "/home/harikrishnan/Downloads/recbole_latest/RecBole/recbole/model/abstract_recommender.py", line 366, in concat_embed_input_fields
sparse_embedding, dense_embedding = self.embed_input_fields(interaction)
File "/home/harikrishnan/Downloads/recbole_latest/RecBole/recbole/model/abstract_recommender.py", line 401, in embed_input_fields
token_fields = torch.cat(token_fields, dim=1) # [batch_size, num_token_field]
RuntimeError: torch.cat(): Sizes of tensors must match except in dimension 1. Got 4004 and 16247 in dimension 0 (The offending index is 1)

**Comment by iamharikrishnank** [comment]
@chenyuwuxin format of  inter and item is as follows
item dataset format : item_id:token	title:token	description:token	topics:token
inter dataset format: user_id:token	item_id:token

**Comment by iamharikrishnank** [comment]
@chenyuwuxin The batch_size of interaction: 4004

**Comment by iamharikrishnank** [comment]
@chenyuwuxin total number of items in dataset is 363

**Comment by iamharikrishnank** [comment]
@chenyuwuxin I am getting this error 
topk_score, topk_iid_list = full_sort_topk(uid_series, model, test_data, k=10, device=config['device'])
Traceback (most recent call last):
File "", line 1, in
File "/home/harikrishnan/Downloads/recbole_latest/RecBole/recbole/utils/case_study.py", line 94, in full_sort_topk
scores = full_sort_scores(uid_series, model, test_data, device)
File "/home/harikrishnan/Downloads/recbole_latest/RecBole/env/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
return func(*args, **kwargs)
File "/home/harikrishnan/Downloads/recbole_latest/RecBole/recbole/utils/case_study.py", line 47, in full_sort_scores
context_feat = Interaction({'description': description, 'title': title})
NameError: name 'description' is not defined

**Comment by iamharikrishnank** [comment]
@chenyuwuxin  how can i print test and train datasets
